# Makefile.in generated by automake 1.16.5 from Makefile.am.
# src/sst/elements/SnnDL/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2021 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Active extension domains.  Each target is independent of the archived
# legacy PE and workload object graph.


am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/sst-elements-library
pkgincludedir = $(includedir)/sst-elements-library
pkglibdir = $(libdir)/sst-elements-library
pkglibexecdir = $(libexecdir)/sst-elements-library
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
subdir = src/sst/elements/SnnDL
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/config/acx_mpi.m4 \
	$(top_srcdir)/config/ax_compiler_vendor.m4 \
	$(top_srcdir)/config/libtool.m4 $(top_srcdir)/config/ltargz.m4 \
	$(top_srcdir)/config/ltdl.m4 $(top_srcdir)/config/ltoptions.m4 \
	$(top_srcdir)/config/ltsugar.m4 \
	$(top_srcdir)/config/ltversion.m4 \
	$(top_srcdir)/config/lt~obsolete.m4 \
	$(top_srcdir)/config/sst-check_picky.m4 \
	$(top_srcdir)/config/sst_check_ariel_mpi.m4 \
	$(top_srcdir)/config/sst_check_cuda.m4 \
	$(top_srcdir)/config/sst_check_dramsim.m4 \
	$(top_srcdir)/config/sst_check_dramsim3.m4 \
	$(top_srcdir)/config/sst_check_dumpi.m4 \
	$(top_srcdir)/config/sst_check_fdsim.m4 \
	$(top_srcdir)/config/sst_check_goblin_hmcsim.m4 \
	$(top_srcdir)/config/sst_check_gpgpusim.m4 \
	$(top_srcdir)/config/sst_check_hbmdramsim.m4 \
	$(top_srcdir)/config/sst_check_hybridsim.m4 \
	$(top_srcdir)/config/sst_check_libz.m4 \
	$(top_srcdir)/config/sst_check_numpy.m4 \
	$(top_srcdir)/config/sst_check_nvdimmsim.m4 \
	$(top_srcdir)/config/sst_check_otf.m4 \
	$(top_srcdir)/config/sst_check_otf2.m4 \
	$(top_srcdir)/config/sst_check_pintool.m4 \
	$(top_srcdir)/config/sst_check_ptrace_set_tracer.m4 \
	$(top_srcdir)/config/sst_check_ramulator.m4 \
	$(top_srcdir)/config/sst_check_ramulator2.m4 \
	$(top_srcdir)/config/sst_check_shm.m4 \
	$(top_srcdir)/config/sst_check_spinlock.m4 \
	$(top_srcdir)/config/sst_check_stake.m4 \
	$(top_srcdir)/config/sst_core_check_install.m4 \
	$(top_srcdir)/config/sst_elements_config_output.m4 \
	$(top_srcdir)/config/sst_os_check_osx.m4 \
	$(top_srcdir)/config/sst_elements_include.m4 \
	$(top_srcdir)/src/sst/elements/ariel/configure.m4 \
	$(top_srcdir)/src/sst/elements/balar/configure.m4 \
	$(top_srcdir)/src/sst/elements/ember/configure.m4 \
	$(top_srcdir)/src/sst/elements/golem/configure.m4 \
	$(top_srcdir)/src/sst/elements/iris/configure.m4 \
	$(top_srcdir)/src/sst/elements/memHierarchy/configure.m4 \
	$(top_srcdir)/src/sst/elements/mercury/configure.m4 \
	$(top_srcdir)/src/sst/elements/messier/configure.m4 \
	$(top_srcdir)/src/sst/elements/miranda/configure.m4 \
	$(top_srcdir)/src/sst/elements/mmu/configure.m4 \
	$(top_srcdir)/src/sst/elements/prospero/configure.m4 \
	$(top_srcdir)/src/sst/elements/samba/configure.m4 \
	$(top_srcdir)/src/sst/elements/SnnDL/configure.m4 \
	$(top_srcdir)/src/sst/elements/zodiac/configure.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(am__DIST_COMMON)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/sst_element_config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(compdir)"
LTLIBRARIES = $(comp_LTLIBRARIES)
libSnnDL_la_DEPENDENCIES = libSnnDLCore.la libSnnDLComm.la \
	libSnnDLLocal.la libSnnDLRegistry.la libSnnDLPlatform2D.la
am__dirstamp = $(am__leading_dot)dirstamp
am_libSnnDL_la_OBJECTS = components/SnnDLCompatibility.lo
libSnnDL_la_OBJECTS = $(am_libSnnDL_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libSnnDL_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libSnnDL_la_LDFLAGS) $(LDFLAGS) -o $@
libSnnDLComm_la_DEPENDENCIES = libSnnDLCore.la libSnnDLRegistry.la
am_libSnnDLComm_la_OBJECTS = events/SpikeEventWrapper.lo \
	components/SnnNIC.lo components/noc/MulticastNIC.lo \
	components/noc/MulticastRouter.lo \
	components/noc/SimpleNetworkWrapper.lo \
	components/noc/SnnNetworkAdapter.lo \
	platform/noc/NocSubsystem.lo \
	platform/noc/OptimizedInternalRing.lo \
	snn/stimulus/ExternalSpikeInputSubsystem.lo \
	snn/synapse/route/BcsrRouteBuilder.lo \
	snn/synapse/route/SnnRouteProvider.lo \
	snn/synapse/route/SpikeCommSubsystem.lo \
	snn/synapse/route/SpikeNocCodec.lo \
	snn/synapse/route/SpikePacketBridge.lo \
	snn/synapse/route/StepBcsrReachability.lo \
	snn/synapse/route/SynapseRouteSubsystem.lo
libSnnDLComm_la_OBJECTS = $(am_libSnnDLComm_la_OBJECTS)
libSnnDLComm_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libSnnDLComm_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libSnnDLCore_la_LIBADD =
am_libSnnDLCore_la_OBJECTS = events/SimpleTestEvent.lo \
	snn/compute/SnnCoreEngine.lo snn/compute/SnnLearningCore.lo
libSnnDLCore_la_OBJECTS = $(am_libSnnDLCore_la_OBJECTS)
libSnnDLCore_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libSnnDLCore_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libSnnDLLocal_la_LIBADD =
am_libSnnDLLocal_la_OBJECTS = platform/memory/DmaMemAccessProxy.lo \
	platform/memory/PeDmaScheduler.lo \
	platform/memory/StandardMemAccess.lo \
	platform/memory/sram_sim/model/BankedSramModel.lo \
	research/local_storage/LocalStorageHierarchyController.lo \
	research/local_storage/PeWeightObjectPlane.lo
libSnnDLLocal_la_OBJECTS = $(am_libSnnDLLocal_la_OBJECTS)
libSnnDLLocal_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libSnnDLLocal_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libSnnDLNextCore_la_LIBADD =
am__objects_1 = snn/timestep/TimestepTracker.lo \
	snn/compute/DeltaAccumulator.lo \
	snn/compute/NextGenNeuronEngine.lo
am_libSnnDLNextCore_la_OBJECTS = $(am__objects_1)
libSnnDLNextCore_la_OBJECTS = $(am_libSnnDLNextCore_la_OBJECTS)
libSnnDLNextCore_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libSnnDLNextCore_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libSnnDLPlatform2D_la_DEPENDENCIES = libSnnDLNextCore.la
am_libSnnDLPlatform2D_la_OBJECTS = platform/core/SnnCoreTile.lo \
	components/MeshPE2D.lo \
	components/timestep/TimestepCoordinator.lo
libSnnDLPlatform2D_la_OBJECTS = $(am_libSnnDLPlatform2D_la_OBJECTS)
libSnnDLPlatform2D_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libSnnDLPlatform2D_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libSnnDLRegistry_la_LIBADD =
am_libSnnDLRegistry_la_OBJECTS =  \
	platform/registry/BcsrSourceContract.lo
libSnnDLRegistry_la_OBJECTS = $(am_libSnnDLRegistry_la_OBJECTS)
libSnnDLRegistry_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libSnnDLRegistry_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libSnnDLResearch_la_DEPENDENCIES = libSnnDLCore.la libSnnDLComm.la \
	libSnnDLRegistry.la
am_libSnnDLResearch_la_OBJECTS = research/noc3d/HBMStackStub.lo \
	research/noc3d/MulticastRouter3DNative.lo \
	research/noc3d/Noc3DSmokeSink.lo \
	research/noc3d/Noc3DSmokeSource.lo \
	research/route3d/SynapseRouteSubsystem3D.lo
libSnnDLResearch_la_OBJECTS = $(am_libSnnDLResearch_la_OBJECTS)
libSnnDLResearch_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(AM_CXXFLAGS) $(CXXFLAGS) $(libSnnDLResearch_la_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = components/$(DEPDIR)/MeshPE2D.Plo \
	components/$(DEPDIR)/SnnDLCompatibility.Plo \
	components/$(DEPDIR)/SnnNIC.Plo \
	components/noc/$(DEPDIR)/MulticastNIC.Plo \
	components/noc/$(DEPDIR)/MulticastRouter.Plo \
	components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo \
	components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo \
	components/timestep/$(DEPDIR)/TimestepCoordinator.Plo \
	events/$(DEPDIR)/SimpleTestEvent.Plo \
	events/$(DEPDIR)/SpikeEventWrapper.Plo \
	platform/core/$(DEPDIR)/SnnCoreTile.Plo \
	platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo \
	platform/memory/$(DEPDIR)/PeDmaScheduler.Plo \
	platform/memory/$(DEPDIR)/StandardMemAccess.Plo \
	platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo \
	platform/noc/$(DEPDIR)/NocSubsystem.Plo \
	platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo \
	platform/registry/$(DEPDIR)/BcsrSourceContract.Plo \
	research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo \
	research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo \
	research/noc3d/$(DEPDIR)/HBMStackStub.Plo \
	research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo \
	research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo \
	research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo \
	research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo \
	snn/compute/$(DEPDIR)/DeltaAccumulator.Plo \
	snn/compute/$(DEPDIR)/NextGenNeuronEngine.Plo \
	snn/compute/$(DEPDIR)/SnnCoreEngine.Plo \
	snn/compute/$(DEPDIR)/SnnLearningCore.Plo \
	snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo \
	snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo \
	snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo \
	snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo \
	snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo \
	snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo \
	snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo \
	snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo \
	snn/timestep/$(DEPDIR)/TimestepTracker.Plo
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libSnnDL_la_SOURCES) $(libSnnDLComm_la_SOURCES) \
	$(libSnnDLCore_la_SOURCES) $(libSnnDLLocal_la_SOURCES) \
	$(libSnnDLNextCore_la_SOURCES) \
	$(libSnnDLPlatform2D_la_SOURCES) \
	$(libSnnDLRegistry_la_SOURCES) $(libSnnDLResearch_la_SOURCES)
DIST_SOURCES = $(libSnnDL_la_SOURCES) $(libSnnDLComm_la_SOURCES) \
	$(libSnnDLCore_la_SOURCES) $(libSnnDLLocal_la_SOURCES) \
	$(libSnnDLNextCore_la_SOURCES) \
	$(libSnnDLPlatform2D_la_SOURCES) \
	$(libSnnDLRegistry_la_SOURCES) $(libSnnDLResearch_la_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__extra_recursive_targets = snippets-recursive
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
am__DIST_COMMON = $(srcdir)/Makefile.in \
	$(srcdir)/build/core_sources.am \
	$(srcdir)/build/extension_sources.am \
	$(srcdir)/build/nextgen_sources.am \
	$(top_srcdir)/config/depcomp README.md
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' aclocal-1.16
AMTAR = $${TAR-tar}
AM_CFLAGS =  
AM_CPPFLAGS =  -I/usr/include/python3.10 -I/usr/include/python3.10 -I/home/xgy/remote/sst_install_mpi/include/sst/core -I/home/xgy/remote/sst_install_mpi/include -I$(top_srcdir)/src -I$(srcdir) \
	-I$(srcdir)/api -I$(srcdir)/events -I$(srcdir)/components \
	-I$(srcdir)/platform/memory -I$(srcdir)/platform/noc \
	-I$(srcdir)/platform/core -I$(srcdir)/components/timestep \
	-I$(srcdir)/snn/compute -I$(srcdir)/snn/profiling \
	-I$(srcdir)/snn/synapse/route -I$(srcdir)/research \
	-I$(SST_PREFIX)/include
AM_CXXFLAGS =  -std=c++17 
AM_DEFAULT_VERBOSITY = 0
AM_LDFLAGS =  -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lpython3.10 -lcrypt -ldl  -lm -lm 
AR = ar
ARIEL_MPICC = 
ARIEL_MPICXX = 
ARIEL_MPI_CFLAGS = 
ARIEL_MPI_LIBS = 
AUTOCONF = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' autoconf
AUTOHEADER = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' autoheader
AUTOMAKE = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' automake-1.16
AWK = gawk
CC = gcc
CCAS = gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g -O2
CCDEPMODE = depmode=gcc3
CC_VERSION = gcc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
CFLAGS = -g -O2
CPP = gcc
CPPFLAGS = -I/home/xgy/remote-20260430/remote/sst_install_mpi/include
CSCOPE = cscope
CTAGS = ctags
CUDA_CPPFLAGS = 
CUDA_LDFLAGS = 
CUDA_LIBDIR = 
CUDA_LIBS = 
CXX = g++ -std=c++17
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DRAMSIM3_CPPFLAGS = 
DRAMSIM3_LDFLAGS = 
DRAMSIM3_LIB = 
DRAMSIM3_LIBDIR = 
DRAMSIM_CPPFLAGS = 
DRAMSIM_LDFLAGS = 
DRAMSIM_LIB = 
DRAMSIM_LIBDIR = 
DSYMUTIL = 
DUMPBIN = 
DUMPI_CPPFLAGS = 
DUMPI_LDFLAGS = 
DUMPI_LIB = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
ETAGS = etags
EXEEXT = 
FDSIM_CPPFLAGS = 
FDSIM_CXXFLAGS = 
FDSIM_LDFLAGS = 
FDSIM_LIB = 
FDSIM_LIBDIR = 
FGREP = /usr/bin/grep -F
GOBLIN_HMCSIM_CPPFLAGS = 
GOBLIN_HMCSIM_LDFLAGS = 
GOBLIN_HMCSIM_LIB = 
GOBLIN_HMCSIM_LIBDIR = 
GPGPUSIM_CPPFLAGS = 
GPGPUSIM_LDFLAGS = 
GPGPUSIM_LIB = 
GPGPUSIM_LIBDIR = 
GREP = /usr/bin/grep
HAVE_SET_PTRACER = 1
HBMDRAMSIM_CPPFLAGS = 
HBMDRAMSIM_LDFLAGS = 
HBMDRAMSIM_LIB = 
HBMDRAMSIM_LIBDIR = 
HDF5_CPPFLAGS = 
HDF5_LDFLAGS = 
HDF5_LIBS = 
HYBRIDSIM_CPPFLAGS = 
HYBRIDSIM_LDFLAGS = 
HYBRIDSIM_LIB = 
HYBRIDSIM_LIBDIR = 
INCLTDL = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = -L/home/xgy/remote-20260430/remote/sst_install_mpi/lib
LIBADD_DL =  
LIBADD_DLD_LINK = 
LIBADD_DLOPEN = 
LIBADD_SHL_LOAD = 
LIBLTDL = -lltdl
LIBOBJS = 
LIBS =  
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBZ_CPPFLAGS = 
LIBZ_LDFLAGS = 
LIBZ_LIB = -lz
LIPO = 
LN_S = ln -s
LTDLDEPS = 
LTDLINCL = 
LTDLOPEN = libltdl
LTLIBOBJS = 
LT_ARGZ_H = 
LT_CONFIG_H = src/sst_element_config.h
LT_DLLOADERS =  dlopen.la
LT_DLPREOPEN = -dlpreopen dlopen.la 
LT_SYS_LIBRARY_PATH = 
MAKEINFO = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
MPICC = mpicc
MPICPP = 
MPICXX = mpic++
MPICXXCPP = 
MPILIBS = 
MPI_CPPFLAGS = 
NM = /usr/bin/nm -B
NMEDIT = 
NUMPY_CPPFLAGS = -I/usr/local/lib/python3.10/dist-packages/numpy/core/include -DHAVE_NUMPY
NVDIMMSIM_CPPFLAGS = 
NVDIMMSIM_CXXFLAGS = 
NVDIMMSIM_LDFLAGS = 
NVDIMMSIM_LIB = 
NVDIMMSIM_LIBDIR = 
OBJDUMP = objdump
OBJEXT = o
OTF2_CONFIG_TOOL = 
OTF2_CPPFLAGS = 
OTF2_LDFLAGS = 
OTF2_PATH = 
OTF_CONFIG_TOOL = 
OTF_CPPFLAGS = 
OTF_LDFLAGS = 
OTF_PATH = 
OTOOL = 
OTOOL64 = 
PACKAGE = sst-elements-library
PACKAGE_BUGREPORT = sst@sandia.gov
PACKAGE_NAME = SST Elements Library
PACKAGE_STRING = SST Elements Library 15.0.0
PACKAGE_TARNAME = sst-elements-library
PACKAGE_URL = 
PACKAGE_VERSION = 15.0.0
PATH_SEPARATOR = :
PINTOOL2_RUNTIME = 
PINTOOL3_RUNTIME = 
PINTOOL_CPPFLAGS = 
PINTOOL_DIR = 
PINTOOL_LDFLAGS = 
PINTOOL_PATH = /home/xgy/.opencode/bin:/home/xgy/.mimocode/bin:/home/xgy/.local/bin:/usr/local/lib/node_modules/@openai/codex/node_modules/@openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/codex-path:/home/xgy/.codex/tmp/arg0/codex-arg0Jh2LgT:/home/xgy/.local/bin:/home/xgy/.opencode/bin:/home/xgy/.mimocode/bin:/home/xgy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PINTOOL_RUNTIME = 
PIN_CPPFLAGS = -g   -Wall   -Werror   -Wno-unknown-pragmas   -D__PIN__=1 -DPIN_CRT=1   -fno-stack-protector   -fno-exceptions   -funwind-tables   -fasynchronous-unwind-tables   -fomit-frame-pointer   -fno-strict-aliasing   -fno-rtti   -faligned-new   -fpic   -DTARGET_IA32E   -DHOST_IA32E   -DTARGET_LINUX   -DPIN_VERSION_MINOR=
PIN_CPPFLAGS_COMPILER = -fno-exceptions          -fabi-version=2
RAMULATOR2_CPPFLAGS = 
RAMULATOR2_LDFLAGS = 
RAMULATOR2_LIB = 
RAMULATOR2_LIBDIR = 
RAMULATOR_CPPFLAGS = 
RAMULATOR_LDFLAGS = 
RAMULATOR_LIB = 
RAMULATOR_LIBDIR = 
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/bash
SHM_LIB =  
SSTELEMENTS_GIT_BRANCH = snndl_re
SSTELEMENTS_GIT_COMMITCOUNT = 15406
SSTELEMENTS_GIT_HEADSHA = c2dfe8028b5438049262daa0e4483ccdbfa0dae6
SST_ACTIVE_ELEMENT_LIBRARIES =  ariel cacheTracer cassini cramSim ember firefly gensa golem hermes iris kingsley mask-mpi memHierarchy mercury merlin messier miranda mmu osseous prospero rdmaNic samba shogun simpleElementExample simpleSimulation SnnDL thornhill vanadis vaultsim zodiac
SST_CONFIG_TOOL = /home/xgy/remote-20260430/remote/sst_install_mpi/bin/sst-config
SST_DIST_ELEMENT_LIBRARIES =  ariel balar cacheTracer cassini cramSim ember firefly gensa golem hermes iris kingsley mask-mpi memHierarchy mercury merlin messier miranda mmu osseous prospero rdmaNic samba shogun simpleElementExample simpleSimulation SnnDL thornhill vanadis vaultsim zodiac
SST_PREFIX = /home/xgy/remote/sst_install_mpi
SST_REGISTER_TOOL = /home/xgy/remote-20260430/remote/sst_install_mpi/bin/sst-register
SST_SNIPPETS_TOOL = /home/xgy/remote-20260430/remote/sst_install_mpi/bin/sst-snippets.py
STAKE_CPPFLAGS = 
STAKE_LDFLAGS = 
STAKE_LIB = 
STAKE_LIBDIR = 
STRIP = strip
VERSION = 15.0.0
abs_builddir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements/src/sst/elements/SnnDL
abs_srcdir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements/src/sst/elements/SnnDL
abs_top_builddir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements
abs_top_srcdir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=posix -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
ltdl_LIBOBJS =  lt__strl.o
ltdl_LTLIBOBJS =  lt__strl.lo
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/xgy/remote-20260430/remote/sst_install_mpi
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sst_check_numpy_happy = yes
sys_symbol_underscore = no
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../../../
top_builddir = ../../../..
top_srcdir = ../../../..
compdir = $(pkglibdir)

# Stable SnnDL core primitives.  No PE assembly, workload registry, weight
# front-end, or research implementation is compiled here.
libSnnDLCore_la_SOURCES = \
	api/GlobalNeuronLayout.h \
	api/SnnDLLogging.h \
	api/SnnDLStringUtil.h \
	events/SimpleTestEvent.cc \
	events/SimpleTestEvent.h \
	snn/compute/SnnCoreEngine.cc \
	snn/compute/SnnCoreEngine.h \
	snn/compute/SnnLearningCore.cc \
	snn/compute/SnnLearningCore.h \
	snn/compute/SnnNeuronModel.h \
	snn/compute/SynapseManager.h \
	snn/profiling/SnnProfiler.h \
	snn/synapse/common/BcsrMeta.h

libSnnDLComm_la_SOURCES = \
	api/INocTransport.h \
	api/ISpikeTransport.h \
	api/ISynapseRoute.h \
	api/MulticastLimits.h \
	api/NocSpikeTransport.h \
	api/SnnInterface.h \
	api/SynapseRouteBuildConfig.h \
	events/NocPacketBatchEvent.h \
	events/NocPacketEvent.h \
	events/SpikeEvent.h \
	events/SpikeEventWrapper.cc \
	events/SpikeEventWrapper.h \
	events/SpikePacket.h \
	components/SnnNIC.cc \
	components/SnnNIC.h \
	components/SnnNICConfig.h \
	components/noc/LocalEndpointMulticastCodec.h \
	components/noc/MulticastNIC.cc \
	components/noc/MulticastNIC.h \
	components/noc/MulticastNICConfig.h \
	components/noc/MulticastRouter.cc \
	components/noc/MulticastRouter.h \
	components/noc/MulticastRouterConfig.h \
	components/noc/SimpleNetworkWrapper.cc \
	components/noc/SimpleNetworkWrapper.h \
	components/noc/SnnNetworkAdapter.cc \
	components/noc/SnnNetworkAdapter.h \
	components/noc/SnnNetworkAdapterConfig.h \
	platform/noc/NocSubsystem.cc \
	platform/noc/NocSubsystem.h \
	platform/noc/OptimizedInternalRing.cc \
	platform/noc/OptimizedInternalRing.h \
	snn/stimulus/ExternalSpikeInputSubsystem.cc \
	snn/stimulus/ExternalSpikeInputSubsystem.h \
	snn/synapse/common/BcsrDataSource.h \
	snn/synapse/route/BcsrRouteBuilder.cc \
	snn/synapse/route/BcsrRouteBuilder.h \
	snn/synapse/route/SnnRouteProvider.cc \
	snn/synapse/route/SnnRouteProvider.h \
	snn/synapse/route/SpikeCommSubsystem.cc \
	snn/synapse/route/SpikeCommSubsystem.h \
	snn/synapse/route/SpikeInterBundleCodec.h \
	snn/synapse/route/SpikeNocCodec.cc \
	snn/synapse/route/SpikeNocCodec.h \
	snn/synapse/route/SpikePacketBridge.cc \
	snn/synapse/route/SpikePacketBridge.h \
	snn/synapse/route/SpikePacketTransport.h \
	snn/synapse/route/SpikeTileBatchEmitter.h \
	snn/synapse/route/SpikeTileNocCodec.h \
	snn/synapse/route/StepBcsrReachability.cc \
	snn/synapse/route/StepBcsrReachability.h \
	snn/synapse/route/SynapseRouteSubsystem.cc \
	snn/synapse/route/SynapseRouteSubsystem.h

libSnnDLLocal_la_SOURCES = \
	api/IDmaSchedulerProvider.h \
	api/IDmaTaggedAccess.h \
	api/ILocalStorageProvider.h \
	api/IMemoryAccess.h \
	api/IPePodSharedMetadataProvider.h \
	api/IPeWeightObjectPlaneProvider.h \
	platform/memory/DmaMemAccessProxy.cc \
	platform/memory/DmaMemAccessProxy.h \
	platform/memory/PeDmaScheduler.cc \
	platform/memory/PeDmaScheduler.h \
	platform/memory/StandardMemAccess.cc \
	platform/memory/StandardMemAccess.h \
	platform/memory/sram_sim/layout/VirtualSramLayout.h \
	platform/memory/sram_sim/model/BankedSramModel.cc \
	platform/memory/sram_sim/model/BankedSramModel.h \
	research/local_storage/LocalStorageHierarchyController.cc \
	research/local_storage/LocalStorageHierarchyController.h \
	research/local_storage/LocalStorageTypes.h \
	research/local_storage/PeInternalPodShadowGate.h \
	research/local_storage/PeLocalServiceObjectTable.h \
	research/local_storage/PeWeightObjectPlane.cc \
	research/local_storage/PeWeightObjectPlane.h \
	research/local_storage/PodMetadataObjectPlane.h \
	research/local_storage/PodOwnerServiceTable.h

libSnnDLRegistry_la_SOURCES = \
	api/BcsrSourceContract.h \
	platform/registry/BcsrSourceContract.cc

libSnnDLResearch_la_SOURCES = \
	research/noc3d/HBMStackStub.cc \
	research/noc3d/HBMStackStub.h \
	research/noc3d/MulticastRouter3DNative.cc \
	research/noc3d/MulticastRouter3DNative.h \
	research/noc3d/MulticastRouter3DNativeConfig.h \
	research/noc3d/Noc3DSmokeSink.cc \
	research/noc3d/Noc3DSmokeSink.h \
	research/noc3d/Noc3DSmokeSource.cc \
	research/noc3d/Noc3DSmokeSource.h \
	research/route3d/Route3DNodeMapper.h \
	research/route3d/SynapseRouteSubsystem3D.cc \
	research/route3d/SynapseRouteSubsystem3D.h


# Next-generation synchronous domain core.  This manifest is intentionally
# independent of the legacy optional-domain source manifests.
SNNDL_NEXT_CORE_SOURCES = \
	api/TimestepTypes.h \
	events/TimestepControlEvent.h \
	snn/timestep/TimestepTracker.h \
	snn/timestep/TimestepTracker.cc \
	snn/compute/DeltaAccumulator.h \
	snn/compute/DeltaAccumulator.cc \
	snn/compute/NextGenNeuronEngine.h \
	snn/compute/NextGenNeuronEngine.cc


# These manifests are the reviewable active-build boundary.  The former PE and
# workload graph is retained under archive/legacy_gas/ only.
EXTRA_DIST = \
	build/core_sources.am \
	build/extension_sources.am \
	build/nextgen_sources.am \
	tools/check_build_boundaries.py \
	tools/run_nextgen_core_tests.sh \
	archive/legacy_gas/README.md \
	docs/SNNDL_V4_STORAGE_CONTRACT.md

comp_LTLIBRARIES = \
	libSnnDLCore.la \
	libSnnDLComm.la \
	libSnnDLLocal.la \
	libSnnDLRegistry.la \
	libSnnDLResearch.la \
	libSnnDLPlatform2D.la \
	libSnnDLNextCore.la \
	libSnnDL.la

libSnnDLCore_la_LDFLAGS = -module -avoid-version -L$(builddir)
libSnnDLComm_la_LDFLAGS = -module -avoid-version -L$(builddir)
libSnnDLComm_la_LIBADD = libSnnDLCore.la libSnnDLRegistry.la
libSnnDLLocal_la_LDFLAGS = -module -avoid-version -L$(builddir)
libSnnDLRegistry_la_LDFLAGS = -module -avoid-version -L$(builddir)
libSnnDLResearch_la_LDFLAGS = -module -avoid-version -L$(builddir)
libSnnDLResearch_la_LIBADD = libSnnDLCore.la libSnnDLComm.la libSnnDLRegistry.la

# SST-native schema-v4 2D platform.  This target owns the event graph and
# links only against the GAS-free domain core; legacy PE/workload sources are
# intentionally absent.
libSnnDLPlatform2D_la_SOURCES = \
	events/TimestepControlEvent.h \
	events/SnnMeshEvents.h \
	platform/core/SnnCoreTile.cc \
	platform/core/SnnCoreTile.h \
	components/MeshPE2D.cc \
	components/MeshPE2D.h \
	components/timestep/TimestepCoordinator.cc \
	components/timestep/TimestepCoordinator.h

libSnnDLPlatform2D_la_LDFLAGS = -module -avoid-version -L$(builddir)
libSnnDLPlatform2D_la_LIBADD = libSnnDLNextCore.la

# Pure synchronous timestep/domain contract.  It has no SST, workload, or
# research dependency and is tested independently below.
libSnnDLNextCore_la_SOURCES = $(SNNDL_NEXT_CORE_SOURCES)
libSnnDLNextCore_la_LDFLAGS = -module -avoid-version -L$(builddir)

# Aggregate compatibility name for SST installations.  The implementation is
# intentionally an empty anchor; all active ELI objects live in the libraries
# above, while no archived target is linked here.
libSnnDL_la_SOURCES = components/SnnDLCompatibility.cc
# SST loads the aggregate `libSnnDL.so` by element-library name.  Keep the
# domain libraries as DT_NEEDED entries so their ELI registration constructors
# are loaded with that entry point; otherwise the empty compatibility anchor
# hides all active components from Python configurations.
libSnnDL_la_LDFLAGS = -module -avoid-version -Wl,--no-as-needed -L$(builddir)
libSnnDL_la_LIBADD = \
	libSnnDLCore.la \
	libSnnDLComm.la \
	libSnnDLLocal.la \
	libSnnDLRegistry.la \
	libSnnDLPlatform2D.la

TEST_LINK = $(CXXLD) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(CXXFLAGS)

all: all-am

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/build/core_sources.am $(srcdir)/build/extension_sources.am $(srcdir)/build/nextgen_sources.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/sst/elements/SnnDL/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/sst/elements/SnnDL/Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles);; \
	esac;
$(srcdir)/build/core_sources.am $(srcdir)/build/extension_sources.am $(srcdir)/build/nextgen_sources.am $(am__empty):

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

install-compLTLIBRARIES: $(comp_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(comp_LTLIBRARIES)'; test -n "$(compdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(compdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(compdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(compdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(compdir)"; \
	}

uninstall-compLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(comp_LTLIBRARIES)'; test -n "$(compdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(compdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(compdir)/$$f"; \
	done

clean-compLTLIBRARIES:
	-test -z "$(comp_LTLIBRARIES)" || rm -f $(comp_LTLIBRARIES)
	@list='$(comp_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
components/$(am__dirstamp):
	@$(MKDIR_P) components
	@: > components/$(am__dirstamp)
components/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/$(DEPDIR)
	@: > components/$(DEPDIR)/$(am__dirstamp)
components/SnnDLCompatibility.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)

libSnnDL.la: $(libSnnDL_la_OBJECTS) $(libSnnDL_la_DEPENDENCIES) $(EXTRA_libSnnDL_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDL_la_LINK) -rpath $(compdir) $(libSnnDL_la_OBJECTS) $(libSnnDL_la_LIBADD) $(LIBS)
events/$(am__dirstamp):
	@$(MKDIR_P) events
	@: > events/$(am__dirstamp)
events/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) events/$(DEPDIR)
	@: > events/$(DEPDIR)/$(am__dirstamp)
events/SpikeEventWrapper.lo: events/$(am__dirstamp) \
	events/$(DEPDIR)/$(am__dirstamp)
components/SnnNIC.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/noc/$(am__dirstamp):
	@$(MKDIR_P) components/noc
	@: > components/noc/$(am__dirstamp)
components/noc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/noc/$(DEPDIR)
	@: > components/noc/$(DEPDIR)/$(am__dirstamp)
components/noc/MulticastNIC.lo: components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
components/noc/MulticastRouter.lo: components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
components/noc/SimpleNetworkWrapper.lo:  \
	components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
components/noc/SnnNetworkAdapter.lo: components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
platform/noc/$(am__dirstamp):
	@$(MKDIR_P) platform/noc
	@: > platform/noc/$(am__dirstamp)
platform/noc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/noc/$(DEPDIR)
	@: > platform/noc/$(DEPDIR)/$(am__dirstamp)
platform/noc/NocSubsystem.lo: platform/noc/$(am__dirstamp) \
	platform/noc/$(DEPDIR)/$(am__dirstamp)
platform/noc/OptimizedInternalRing.lo: platform/noc/$(am__dirstamp) \
	platform/noc/$(DEPDIR)/$(am__dirstamp)
snn/stimulus/$(am__dirstamp):
	@$(MKDIR_P) snn/stimulus
	@: > snn/stimulus/$(am__dirstamp)
snn/stimulus/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/stimulus/$(DEPDIR)
	@: > snn/stimulus/$(DEPDIR)/$(am__dirstamp)
snn/stimulus/ExternalSpikeInputSubsystem.lo:  \
	snn/stimulus/$(am__dirstamp) \
	snn/stimulus/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/route
	@: > snn/synapse/route/$(am__dirstamp)
snn/synapse/route/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/route/$(DEPDIR)
	@: > snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/BcsrRouteBuilder.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SnnRouteProvider.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SpikeCommSubsystem.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SpikeNocCodec.lo: snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SpikePacketBridge.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/StepBcsrReachability.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SynapseRouteSubsystem.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)

libSnnDLComm.la: $(libSnnDLComm_la_OBJECTS) $(libSnnDLComm_la_DEPENDENCIES) $(EXTRA_libSnnDLComm_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDLComm_la_LINK) -rpath $(compdir) $(libSnnDLComm_la_OBJECTS) $(libSnnDLComm_la_LIBADD) $(LIBS)
events/SimpleTestEvent.lo: events/$(am__dirstamp) \
	events/$(DEPDIR)/$(am__dirstamp)
snn/compute/$(am__dirstamp):
	@$(MKDIR_P) snn/compute
	@: > snn/compute/$(am__dirstamp)
snn/compute/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/compute/$(DEPDIR)
	@: > snn/compute/$(DEPDIR)/$(am__dirstamp)
snn/compute/SnnCoreEngine.lo: snn/compute/$(am__dirstamp) \
	snn/compute/$(DEPDIR)/$(am__dirstamp)
snn/compute/SnnLearningCore.lo: snn/compute/$(am__dirstamp) \
	snn/compute/$(DEPDIR)/$(am__dirstamp)

libSnnDLCore.la: $(libSnnDLCore_la_OBJECTS) $(libSnnDLCore_la_DEPENDENCIES) $(EXTRA_libSnnDLCore_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDLCore_la_LINK) -rpath $(compdir) $(libSnnDLCore_la_OBJECTS) $(libSnnDLCore_la_LIBADD) $(LIBS)
platform/memory/$(am__dirstamp):
	@$(MKDIR_P) platform/memory
	@: > platform/memory/$(am__dirstamp)
platform/memory/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/memory/$(DEPDIR)
	@: > platform/memory/$(DEPDIR)/$(am__dirstamp)
platform/memory/DmaMemAccessProxy.lo: platform/memory/$(am__dirstamp) \
	platform/memory/$(DEPDIR)/$(am__dirstamp)
platform/memory/PeDmaScheduler.lo: platform/memory/$(am__dirstamp) \
	platform/memory/$(DEPDIR)/$(am__dirstamp)
platform/memory/StandardMemAccess.lo: platform/memory/$(am__dirstamp) \
	platform/memory/$(DEPDIR)/$(am__dirstamp)
platform/memory/sram_sim/model/$(am__dirstamp):
	@$(MKDIR_P) platform/memory/sram_sim/model
	@: > platform/memory/sram_sim/model/$(am__dirstamp)
platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/memory/sram_sim/model/$(DEPDIR)
	@: > platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp)
platform/memory/sram_sim/model/BankedSramModel.lo:  \
	platform/memory/sram_sim/model/$(am__dirstamp) \
	platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp)
research/local_storage/$(am__dirstamp):
	@$(MKDIR_P) research/local_storage
	@: > research/local_storage/$(am__dirstamp)
research/local_storage/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) research/local_storage/$(DEPDIR)
	@: > research/local_storage/$(DEPDIR)/$(am__dirstamp)
research/local_storage/LocalStorageHierarchyController.lo:  \
	research/local_storage/$(am__dirstamp) \
	research/local_storage/$(DEPDIR)/$(am__dirstamp)
research/local_storage/PeWeightObjectPlane.lo:  \
	research/local_storage/$(am__dirstamp) \
	research/local_storage/$(DEPDIR)/$(am__dirstamp)

libSnnDLLocal.la: $(libSnnDLLocal_la_OBJECTS) $(libSnnDLLocal_la_DEPENDENCIES) $(EXTRA_libSnnDLLocal_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDLLocal_la_LINK) -rpath $(compdir) $(libSnnDLLocal_la_OBJECTS) $(libSnnDLLocal_la_LIBADD) $(LIBS)
snn/timestep/$(am__dirstamp):
	@$(MKDIR_P) snn/timestep
	@: > snn/timestep/$(am__dirstamp)
snn/timestep/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/timestep/$(DEPDIR)
	@: > snn/timestep/$(DEPDIR)/$(am__dirstamp)
snn/timestep/TimestepTracker.lo: snn/timestep/$(am__dirstamp) \
	snn/timestep/$(DEPDIR)/$(am__dirstamp)
snn/compute/DeltaAccumulator.lo: snn/compute/$(am__dirstamp) \
	snn/compute/$(DEPDIR)/$(am__dirstamp)
snn/compute/NextGenNeuronEngine.lo: snn/compute/$(am__dirstamp) \
	snn/compute/$(DEPDIR)/$(am__dirstamp)

libSnnDLNextCore.la: $(libSnnDLNextCore_la_OBJECTS) $(libSnnDLNextCore_la_DEPENDENCIES) $(EXTRA_libSnnDLNextCore_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDLNextCore_la_LINK) -rpath $(compdir) $(libSnnDLNextCore_la_OBJECTS) $(libSnnDLNextCore_la_LIBADD) $(LIBS)
platform/core/$(am__dirstamp):
	@$(MKDIR_P) platform/core
	@: > platform/core/$(am__dirstamp)
platform/core/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/core/$(DEPDIR)
	@: > platform/core/$(DEPDIR)/$(am__dirstamp)
platform/core/SnnCoreTile.lo: platform/core/$(am__dirstamp) \
	platform/core/$(DEPDIR)/$(am__dirstamp)
components/MeshPE2D.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/timestep/$(am__dirstamp):
	@$(MKDIR_P) components/timestep
	@: > components/timestep/$(am__dirstamp)
components/timestep/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/timestep/$(DEPDIR)
	@: > components/timestep/$(DEPDIR)/$(am__dirstamp)
components/timestep/TimestepCoordinator.lo:  \
	components/timestep/$(am__dirstamp) \
	components/timestep/$(DEPDIR)/$(am__dirstamp)

libSnnDLPlatform2D.la: $(libSnnDLPlatform2D_la_OBJECTS) $(libSnnDLPlatform2D_la_DEPENDENCIES) $(EXTRA_libSnnDLPlatform2D_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDLPlatform2D_la_LINK) -rpath $(compdir) $(libSnnDLPlatform2D_la_OBJECTS) $(libSnnDLPlatform2D_la_LIBADD) $(LIBS)
platform/registry/$(am__dirstamp):
	@$(MKDIR_P) platform/registry
	@: > platform/registry/$(am__dirstamp)
platform/registry/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/registry/$(DEPDIR)
	@: > platform/registry/$(DEPDIR)/$(am__dirstamp)
platform/registry/BcsrSourceContract.lo:  \
	platform/registry/$(am__dirstamp) \
	platform/registry/$(DEPDIR)/$(am__dirstamp)

libSnnDLRegistry.la: $(libSnnDLRegistry_la_OBJECTS) $(libSnnDLRegistry_la_DEPENDENCIES) $(EXTRA_libSnnDLRegistry_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDLRegistry_la_LINK) -rpath $(compdir) $(libSnnDLRegistry_la_OBJECTS) $(libSnnDLRegistry_la_LIBADD) $(LIBS)
research/noc3d/$(am__dirstamp):
	@$(MKDIR_P) research/noc3d
	@: > research/noc3d/$(am__dirstamp)
research/noc3d/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) research/noc3d/$(DEPDIR)
	@: > research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/HBMStackStub.lo: research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/MulticastRouter3DNative.lo:  \
	research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/Noc3DSmokeSink.lo: research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/Noc3DSmokeSource.lo: research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/route3d/$(am__dirstamp):
	@$(MKDIR_P) research/route3d
	@: > research/route3d/$(am__dirstamp)
research/route3d/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) research/route3d/$(DEPDIR)
	@: > research/route3d/$(DEPDIR)/$(am__dirstamp)
research/route3d/SynapseRouteSubsystem3D.lo:  \
	research/route3d/$(am__dirstamp) \
	research/route3d/$(DEPDIR)/$(am__dirstamp)

libSnnDLResearch.la: $(libSnnDLResearch_la_OBJECTS) $(libSnnDLResearch_la_DEPENDENCIES) $(EXTRA_libSnnDLResearch_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDLResearch_la_LINK) -rpath $(compdir) $(libSnnDLResearch_la_OBJECTS) $(libSnnDLResearch_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f components/*.$(OBJEXT)
	-rm -f components/*.lo
	-rm -f components/noc/*.$(OBJEXT)
	-rm -f components/noc/*.lo
	-rm -f components/timestep/*.$(OBJEXT)
	-rm -f components/timestep/*.lo
	-rm -f events/*.$(OBJEXT)
	-rm -f events/*.lo
	-rm -f platform/core/*.$(OBJEXT)
	-rm -f platform/core/*.lo
	-rm -f platform/memory/*.$(OBJEXT)
	-rm -f platform/memory/*.lo
	-rm -f platform/memory/sram_sim/model/*.$(OBJEXT)
	-rm -f platform/memory/sram_sim/model/*.lo
	-rm -f platform/noc/*.$(OBJEXT)
	-rm -f platform/noc/*.lo
	-rm -f platform/registry/*.$(OBJEXT)
	-rm -f platform/registry/*.lo
	-rm -f research/local_storage/*.$(OBJEXT)
	-rm -f research/local_storage/*.lo
	-rm -f research/noc3d/*.$(OBJEXT)
	-rm -f research/noc3d/*.lo
	-rm -f research/route3d/*.$(OBJEXT)
	-rm -f research/route3d/*.lo
	-rm -f snn/compute/*.$(OBJEXT)
	-rm -f snn/compute/*.lo
	-rm -f snn/stimulus/*.$(OBJEXT)
	-rm -f snn/stimulus/*.lo
	-rm -f snn/synapse/route/*.$(OBJEXT)
	-rm -f snn/synapse/route/*.lo
	-rm -f snn/timestep/*.$(OBJEXT)
	-rm -f snn/timestep/*.lo

distclean-compile:
	-rm -f *.tab.c

include components/$(DEPDIR)/MeshPE2D.Plo # am--include-marker
include components/$(DEPDIR)/SnnDLCompatibility.Plo # am--include-marker
include components/$(DEPDIR)/SnnNIC.Plo # am--include-marker
include components/noc/$(DEPDIR)/MulticastNIC.Plo # am--include-marker
include components/noc/$(DEPDIR)/MulticastRouter.Plo # am--include-marker
include components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo # am--include-marker
include components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo # am--include-marker
include components/timestep/$(DEPDIR)/TimestepCoordinator.Plo # am--include-marker
include events/$(DEPDIR)/SimpleTestEvent.Plo # am--include-marker
include events/$(DEPDIR)/SpikeEventWrapper.Plo # am--include-marker
include platform/core/$(DEPDIR)/SnnCoreTile.Plo # am--include-marker
include platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo # am--include-marker
include platform/memory/$(DEPDIR)/PeDmaScheduler.Plo # am--include-marker
include platform/memory/$(DEPDIR)/StandardMemAccess.Plo # am--include-marker
include platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo # am--include-marker
include platform/noc/$(DEPDIR)/NocSubsystem.Plo # am--include-marker
include platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo # am--include-marker
include platform/registry/$(DEPDIR)/BcsrSourceContract.Plo # am--include-marker
include research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo # am--include-marker
include research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/HBMStackStub.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo # am--include-marker
include research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo # am--include-marker
include snn/compute/$(DEPDIR)/DeltaAccumulator.Plo # am--include-marker
include snn/compute/$(DEPDIR)/NextGenNeuronEngine.Plo # am--include-marker
include snn/compute/$(DEPDIR)/SnnCoreEngine.Plo # am--include-marker
include snn/compute/$(DEPDIR)/SnnLearningCore.Plo # am--include-marker
include snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo # am--include-marker
include snn/timestep/$(DEPDIR)/TimestepTracker.Plo # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cc.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf components/.libs components/_libs
	-rm -rf components/noc/.libs components/noc/_libs
	-rm -rf components/timestep/.libs components/timestep/_libs
	-rm -rf events/.libs events/_libs
	-rm -rf platform/core/.libs platform/core/_libs
	-rm -rf platform/memory/.libs platform/memory/_libs
	-rm -rf platform/memory/sram_sim/model/.libs platform/memory/sram_sim/model/_libs
	-rm -rf platform/noc/.libs platform/noc/_libs
	-rm -rf platform/registry/.libs platform/registry/_libs
	-rm -rf research/local_storage/.libs research/local_storage/_libs
	-rm -rf research/noc3d/.libs research/noc3d/_libs
	-rm -rf research/route3d/.libs research/route3d/_libs
	-rm -rf snn/compute/.libs snn/compute/_libs
	-rm -rf snn/stimulus/.libs snn/stimulus/_libs
	-rm -rf snn/synapse/route/.libs snn/synapse/route/_libs
	-rm -rf snn/timestep/.libs snn/timestep/_libs
snippets-local: 

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES)
installdirs:
	for dir in "$(DESTDIR)$(compdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f components/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/$(am__dirstamp)
	-rm -f components/noc/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/noc/$(am__dirstamp)
	-rm -f components/timestep/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/timestep/$(am__dirstamp)
	-rm -f events/$(DEPDIR)/$(am__dirstamp)
	-rm -f events/$(am__dirstamp)
	-rm -f platform/core/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/core/$(am__dirstamp)
	-rm -f platform/memory/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/memory/$(am__dirstamp)
	-rm -f platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/memory/sram_sim/model/$(am__dirstamp)
	-rm -f platform/noc/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/noc/$(am__dirstamp)
	-rm -f platform/registry/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/registry/$(am__dirstamp)
	-rm -f research/local_storage/$(DEPDIR)/$(am__dirstamp)
	-rm -f research/local_storage/$(am__dirstamp)
	-rm -f research/noc3d/$(DEPDIR)/$(am__dirstamp)
	-rm -f research/noc3d/$(am__dirstamp)
	-rm -f research/route3d/$(DEPDIR)/$(am__dirstamp)
	-rm -f research/route3d/$(am__dirstamp)
	-rm -f snn/compute/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/compute/$(am__dirstamp)
	-rm -f snn/stimulus/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/stimulus/$(am__dirstamp)
	-rm -f snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/synapse/route/$(am__dirstamp)
	-rm -f snn/timestep/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/timestep/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-compLTLIBRARIES clean-generic clean-libtool \
	mostlyclean-am

distclean: distclean-am
		-rm -f components/$(DEPDIR)/MeshPE2D.Plo
	-rm -f components/$(DEPDIR)/SnnDLCompatibility.Plo
	-rm -f components/$(DEPDIR)/SnnNIC.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastNIC.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastRouter.Plo
	-rm -f components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo
	-rm -f components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo
	-rm -f components/timestep/$(DEPDIR)/TimestepCoordinator.Plo
	-rm -f events/$(DEPDIR)/SimpleTestEvent.Plo
	-rm -f events/$(DEPDIR)/SpikeEventWrapper.Plo
	-rm -f platform/core/$(DEPDIR)/SnnCoreTile.Plo
	-rm -f platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo
	-rm -f platform/memory/$(DEPDIR)/PeDmaScheduler.Plo
	-rm -f platform/memory/$(DEPDIR)/StandardMemAccess.Plo
	-rm -f platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo
	-rm -f platform/noc/$(DEPDIR)/NocSubsystem.Plo
	-rm -f platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo
	-rm -f platform/registry/$(DEPDIR)/BcsrSourceContract.Plo
	-rm -f research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo
	-rm -f research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo
	-rm -f research/noc3d/$(DEPDIR)/HBMStackStub.Plo
	-rm -f research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo
	-rm -f research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo
	-rm -f snn/compute/$(DEPDIR)/DeltaAccumulator.Plo
	-rm -f snn/compute/$(DEPDIR)/NextGenNeuronEngine.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnCoreEngine.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnLearningCore.Plo
	-rm -f snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo
	-rm -f snn/timestep/$(DEPDIR)/TimestepTracker.Plo
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-compLTLIBRARIES

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
		-rm -f components/$(DEPDIR)/MeshPE2D.Plo
	-rm -f components/$(DEPDIR)/SnnDLCompatibility.Plo
	-rm -f components/$(DEPDIR)/SnnNIC.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastNIC.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastRouter.Plo
	-rm -f components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo
	-rm -f components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo
	-rm -f components/timestep/$(DEPDIR)/TimestepCoordinator.Plo
	-rm -f events/$(DEPDIR)/SimpleTestEvent.Plo
	-rm -f events/$(DEPDIR)/SpikeEventWrapper.Plo
	-rm -f platform/core/$(DEPDIR)/SnnCoreTile.Plo
	-rm -f platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo
	-rm -f platform/memory/$(DEPDIR)/PeDmaScheduler.Plo
	-rm -f platform/memory/$(DEPDIR)/StandardMemAccess.Plo
	-rm -f platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo
	-rm -f platform/noc/$(DEPDIR)/NocSubsystem.Plo
	-rm -f platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo
	-rm -f platform/registry/$(DEPDIR)/BcsrSourceContract.Plo
	-rm -f research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo
	-rm -f research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo
	-rm -f research/noc3d/$(DEPDIR)/HBMStackStub.Plo
	-rm -f research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo
	-rm -f research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo
	-rm -f snn/compute/$(DEPDIR)/DeltaAccumulator.Plo
	-rm -f snn/compute/$(DEPDIR)/NextGenNeuronEngine.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnCoreEngine.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnLearningCore.Plo
	-rm -f snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo
	-rm -f snn/timestep/$(DEPDIR)/TimestepTracker.Plo
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

snippets: snippets-am

snippets-am: snippets-local

uninstall-am: uninstall-compLTLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles check check-am clean \
	clean-compLTLIBRARIES clean-generic clean-libtool \
	cscopelist-am ctags ctags-am distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-compLTLIBRARIES install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am snippets-am \
	snippets-local tags tags-am uninstall uninstall-am \
	uninstall-compLTLIBRARIES

.PRECIOUS: Makefile


.PHONY: check-boundaries test-compile test-timestep-core \
	test-bcsr-source-contract test-dma-scheduler test-banked-sram \
	test-local-storage

check-boundaries:
	python3 $(srcdir)/tools/check_build_boundaries.py --root $(srcdir)

test-timestep-core:
	$(srcdir)/tools/run_nextgen_core_tests.sh

test-bcsr-source-contract:
	$(TEST_LINK) $(srcdir)/tests/test_bcsr_source_contract.cc \
		$(srcdir)/platform/registry/BcsrSourceContract.cc -pthread \
		-o $(builddir)/test_bcsr_source_contract$(EXEEXT) && \
	$(builddir)/test_bcsr_source_contract$(EXEEXT)

test-dma-scheduler:
	$(TEST_LINK) $(srcdir)/tests/test_pe_dma_scheduler.cc \
		$(srcdir)/platform/memory/DmaMemAccessProxy.cc \
		$(srcdir)/platform/memory/PeDmaScheduler.cc \
		-o $(builddir)/test_pe_dma_scheduler$(EXEEXT) && \
	$(builddir)/test_pe_dma_scheduler$(EXEEXT)

test-banked-sram:
	$(TEST_LINK) $(srcdir)/tests/test_banked_sram_model.cc \
		$(srcdir)/platform/memory/sram_sim/model/BankedSramModel.cc \
		-o $(builddir)/test_banked_sram_model$(EXEEXT) && \
	$(builddir)/test_banked_sram_model$(EXEEXT)

test-local-storage:
	$(TEST_LINK) $(srcdir)/tests/test_local_storage_hierarchy.cc \
		$(srcdir)/research/local_storage/LocalStorageHierarchyController.cc \
		$(srcdir)/research/local_storage/PeWeightObjectPlane.cc \
		$(srcdir)/platform/memory/sram_sim/model/BankedSramModel.cc \
		-o $(builddir)/test_local_storage_hierarchy$(EXEEXT) && \
	$(builddir)/test_local_storage_hierarchy$(EXEEXT)

test-compile:
	$(CXXCOMPILE) -c $(srcdir)/tests/test_bcsr_source_contract.cc -o $(builddir)/test_bcsr_source_contract.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_banked_sram_model.cc -o $(builddir)/test_banked_sram_model.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_local_storage_hierarchy.cc -o $(builddir)/test_local_storage_hierarchy.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_pe_dma_scheduler.cc -o $(builddir)/test_pe_dma_scheduler.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_timestep_core.cc -o $(builddir)/test_timestep_core.o

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
