# Makefile.in generated by automake 1.16.5 from Makefile.am.
# src/sst/elements/SnnDL/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2021 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/sst-elements-library
pkgincludedir = $(includedir)/sst-elements-library
pkglibdir = $(libdir)/sst-elements-library
pkglibexecdir = $(libexecdir)/sst-elements-library
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
subdir = src/sst/elements/SnnDL
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/config/acx_mpi.m4 \
	$(top_srcdir)/config/ax_compiler_vendor.m4 \
	$(top_srcdir)/config/libtool.m4 $(top_srcdir)/config/ltargz.m4 \
	$(top_srcdir)/config/ltdl.m4 $(top_srcdir)/config/ltoptions.m4 \
	$(top_srcdir)/config/ltsugar.m4 \
	$(top_srcdir)/config/ltversion.m4 \
	$(top_srcdir)/config/lt~obsolete.m4 \
	$(top_srcdir)/config/sst-check_picky.m4 \
	$(top_srcdir)/config/sst_check_ariel_mpi.m4 \
	$(top_srcdir)/config/sst_check_cuda.m4 \
	$(top_srcdir)/config/sst_check_dramsim.m4 \
	$(top_srcdir)/config/sst_check_dramsim3.m4 \
	$(top_srcdir)/config/sst_check_dumpi.m4 \
	$(top_srcdir)/config/sst_check_fdsim.m4 \
	$(top_srcdir)/config/sst_check_goblin_hmcsim.m4 \
	$(top_srcdir)/config/sst_check_gpgpusim.m4 \
	$(top_srcdir)/config/sst_check_hbmdramsim.m4 \
	$(top_srcdir)/config/sst_check_hybridsim.m4 \
	$(top_srcdir)/config/sst_check_libz.m4 \
	$(top_srcdir)/config/sst_check_numpy.m4 \
	$(top_srcdir)/config/sst_check_nvdimmsim.m4 \
	$(top_srcdir)/config/sst_check_otf.m4 \
	$(top_srcdir)/config/sst_check_otf2.m4 \
	$(top_srcdir)/config/sst_check_pintool.m4 \
	$(top_srcdir)/config/sst_check_ptrace_set_tracer.m4 \
	$(top_srcdir)/config/sst_check_ramulator.m4 \
	$(top_srcdir)/config/sst_check_ramulator2.m4 \
	$(top_srcdir)/config/sst_check_shm.m4 \
	$(top_srcdir)/config/sst_check_spinlock.m4 \
	$(top_srcdir)/config/sst_check_stake.m4 \
	$(top_srcdir)/config/sst_core_check_install.m4 \
	$(top_srcdir)/config/sst_elements_config_output.m4 \
	$(top_srcdir)/config/sst_os_check_osx.m4 \
	$(top_srcdir)/config/sst_elements_include.m4 \
	$(top_srcdir)/src/sst/elements/ariel/configure.m4 \
	$(top_srcdir)/src/sst/elements/balar/configure.m4 \
	$(top_srcdir)/src/sst/elements/ember/configure.m4 \
	$(top_srcdir)/src/sst/elements/golem/configure.m4 \
	$(top_srcdir)/src/sst/elements/iris/configure.m4 \
	$(top_srcdir)/src/sst/elements/memHierarchy/configure.m4 \
	$(top_srcdir)/src/sst/elements/mercury/configure.m4 \
	$(top_srcdir)/src/sst/elements/messier/configure.m4 \
	$(top_srcdir)/src/sst/elements/miranda/configure.m4 \
	$(top_srcdir)/src/sst/elements/mmu/configure.m4 \
	$(top_srcdir)/src/sst/elements/prospero/configure.m4 \
	$(top_srcdir)/src/sst/elements/samba/configure.m4 \
	$(top_srcdir)/src/sst/elements/SnnDL/configure.m4 \
	$(top_srcdir)/src/sst/elements/zodiac/configure.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(am__DIST_COMMON)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/sst_element_config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(compdir)"
LTLIBRARIES = $(comp_LTLIBRARIES)
libSnnDL_la_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_libSnnDL_la_OBJECTS = events/SimpleTestEvent.lo \
	events/SpikeEventWrapper.lo \
	components/gas/GlobalGasStepController.lo \
	components/CachelineFragmentMemIF.lo \
	components/GatherBufferIF.lo \
	components/gather/GatherBufferIFConfig.lo \
	components/GatingPE.lo components/MemKCalBench.lo \
	components/multicore/MultiCorePEConfig.lo \
	components/multicore/MultiCorePEObservability.lo \
	components/MultiCorePE.lo components/SnnNIC.lo \
	components/stimulus/SpikeSource.lo components/WeightLoader.lo \
	platform/stats/WorkloadStatsRegistry.lo \
	platform/core/SnnPESubComponent.lo \
	platform/core/SnnPESubComponentStats.lo \
	platform/core/SnnPESubComponent_bcsr.lo \
	platform/core/SnnPESubComponent_routing.lo \
	platform/core/SnnPEApplyScatter.lo \
	platform/core/SnnPEOrchestrators.lo \
	snn/compute/SnnComputeCore.lo snn/compute/SnnCoreEngine.lo \
	snn/compute/SnnLearningCore.lo \
	snn/synapse/gas/AccumulatorOps.lo \
	snn/synapse/gas/GasEdgeCollector.lo \
	snn/synapse/gas/GasPhaseController.lo \
	snn/synapse/stdmem/StdMemEndpoint.lo \
	snn/synapse/stdmem/SnnPESubComponent_mem.lo \
	platform/noc/OptimizedInternalRing.lo \
	components/noc/SimpleNetworkWrapper.lo \
	snn/synapse/weights/SnnBcsrWeightManager.lo \
	snn/synapse/weights/SnnWeightDiagnostics.lo \
	components/noc/SnnNetworkAdapter.lo \
	components/noc/MulticastRouter.lo \
	research/noc3d/MulticastRouter3DNative.lo \
	research/noc3d/Noc3DSmokeSource.lo \
	research/noc3d/Noc3DSmokeSink.lo \
	research/noc3d/HBMStackStub.lo components/noc/MulticastNIC.lo \
	snn/synapse/route/SnnRouteProvider.lo \
	snn/synapse/route/SpikeNocCodec.lo \
	snn/synapse/route/BcsrRouteBuilder.lo \
	snn/synapse/route/StepBcsrReachability.lo \
	snn/synapse/route/SynapseRouteSubsystem.lo \
	research/route3d/SynapseRouteSubsystem3D.lo \
	snn/stimulus/StepActivationSubsystem.lo \
	snn/stimulus/ExternalSpikeInputSubsystem.lo \
	platform/noc/NocSubsystem.lo \
	snn/synapse/weights/WeightAccessor.lo \
	snn/synapse/weights/WeightCacheOps.lo \
	snn/synapse/weights/WeightMemorySubsystem.lo \
	snn/synapse/weights/WeightMemorySubsystemVerification.lo \
	snn/synapse/route/SpikeCommSubsystem.lo \
	snn/synapse/route/SpikePacketBridge.lo \
	workloads/CoreWorkloadFactory.lo \
	workloads/common/SnnAccelBackend.lo \
	workloads/layout/NormalizedNeuronLayout.lo \
	workloads/riscv_snn/RiscvSnnBootDriver.lo \
	workloads/riscv_snn/RiscvSnnFirmwareLoader.lo \
	workloads/riscv_snn/RiscvSnnHart.lo \
	workloads/riscv_snn/RiscvSnnIss.lo \
	workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.lo \
	workloads/riscv_snn/RiscvSnnShadowTransportExport.lo \
	workloads/riscv_snn/RiscvSnnShadowRuntimeServices.lo \
	workloads/riscv_snn/RiscvSnnWorkload.lo \
	workloads/snn/SnnWorkload.lo \
	workloads/stream/StreamWorkload.lo \
	workloads/traffic/TrafficWorkload.lo \
	workloads/traffic_mem/TrafficMemWorkload.lo \
	workloads/tensor/TensorWorkload.lo \
	workloads/tensor/TensorWorkloadCollective.lo \
	workloads/tensor/TensorWorkloadConfig.lo \
	workloads/tensor/TensorWorkloadProgram.lo \
	workloads/tensor/TensorWorkloadStats.lo \
	platform/memory/sram_sim/model/BankedSramModel.lo \
	research/local_storage/LocalStorageHierarchyController.lo \
	research/local_storage/PeWeightObjectPlane.lo \
	platform/memory/DmaMemAccessProxy.lo \
	platform/memory/PeDmaScheduler.lo \
	platform/memory/StandardMemAccess.lo
libSnnDL_la_OBJECTS = $(am_libSnnDL_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libSnnDL_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libSnnDL_la_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = components/$(DEPDIR)/CachelineFragmentMemIF.Plo \
	components/$(DEPDIR)/GatherBufferIF.Plo \
	components/$(DEPDIR)/GatingPE.Plo \
	components/$(DEPDIR)/MemKCalBench.Plo \
	components/$(DEPDIR)/MultiCorePE.Plo \
	components/$(DEPDIR)/SnnNIC.Plo \
	components/$(DEPDIR)/WeightLoader.Plo \
	components/gas/$(DEPDIR)/GlobalGasStepController.Plo \
	components/gather/$(DEPDIR)/GatherBufferIFConfig.Plo \
	components/multicore/$(DEPDIR)/MultiCorePEConfig.Plo \
	components/multicore/$(DEPDIR)/MultiCorePEObservability.Plo \
	components/noc/$(DEPDIR)/MulticastNIC.Plo \
	components/noc/$(DEPDIR)/MulticastRouter.Plo \
	components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo \
	components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo \
	components/stimulus/$(DEPDIR)/SpikeSource.Plo \
	events/$(DEPDIR)/SimpleTestEvent.Plo \
	events/$(DEPDIR)/SpikeEventWrapper.Plo \
	platform/core/$(DEPDIR)/SnnPEApplyScatter.Plo \
	platform/core/$(DEPDIR)/SnnPEOrchestrators.Plo \
	platform/core/$(DEPDIR)/SnnPESubComponent.Plo \
	platform/core/$(DEPDIR)/SnnPESubComponentStats.Plo \
	platform/core/$(DEPDIR)/SnnPESubComponent_bcsr.Plo \
	platform/core/$(DEPDIR)/SnnPESubComponent_routing.Plo \
	platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo \
	platform/memory/$(DEPDIR)/PeDmaScheduler.Plo \
	platform/memory/$(DEPDIR)/StandardMemAccess.Plo \
	platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo \
	platform/noc/$(DEPDIR)/NocSubsystem.Plo \
	platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo \
	platform/stats/$(DEPDIR)/WorkloadStatsRegistry.Plo \
	research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo \
	research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo \
	research/noc3d/$(DEPDIR)/HBMStackStub.Plo \
	research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo \
	research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo \
	research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo \
	research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo \
	snn/compute/$(DEPDIR)/SnnComputeCore.Plo \
	snn/compute/$(DEPDIR)/SnnCoreEngine.Plo \
	snn/compute/$(DEPDIR)/SnnLearningCore.Plo \
	snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo \
	snn/stimulus/$(DEPDIR)/StepActivationSubsystem.Plo \
	snn/synapse/gas/$(DEPDIR)/AccumulatorOps.Plo \
	snn/synapse/gas/$(DEPDIR)/GasEdgeCollector.Plo \
	snn/synapse/gas/$(DEPDIR)/GasPhaseController.Plo \
	snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo \
	snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo \
	snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo \
	snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo \
	snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo \
	snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo \
	snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo \
	snn/synapse/stdmem/$(DEPDIR)/SnnPESubComponent_mem.Plo \
	snn/synapse/stdmem/$(DEPDIR)/StdMemEndpoint.Plo \
	snn/synapse/weights/$(DEPDIR)/SnnBcsrWeightManager.Plo \
	snn/synapse/weights/$(DEPDIR)/SnnWeightDiagnostics.Plo \
	snn/synapse/weights/$(DEPDIR)/WeightAccessor.Plo \
	snn/synapse/weights/$(DEPDIR)/WeightCacheOps.Plo \
	snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystem.Plo \
	snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystemVerification.Plo \
	workloads/$(DEPDIR)/CoreWorkloadFactory.Plo \
	workloads/common/$(DEPDIR)/SnnAccelBackend.Plo \
	workloads/layout/$(DEPDIR)/NormalizedNeuronLayout.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnBootDriver.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnFirmwareLoader.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnHart.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnIss.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnRuntimeBridgeBackend.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowRuntimeServices.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowTransportExport.Plo \
	workloads/riscv_snn/$(DEPDIR)/RiscvSnnWorkload.Plo \
	workloads/snn/$(DEPDIR)/SnnWorkload.Plo \
	workloads/stream/$(DEPDIR)/StreamWorkload.Plo \
	workloads/tensor/$(DEPDIR)/TensorWorkload.Plo \
	workloads/tensor/$(DEPDIR)/TensorWorkloadCollective.Plo \
	workloads/tensor/$(DEPDIR)/TensorWorkloadConfig.Plo \
	workloads/tensor/$(DEPDIR)/TensorWorkloadProgram.Plo \
	workloads/tensor/$(DEPDIR)/TensorWorkloadStats.Plo \
	workloads/traffic/$(DEPDIR)/TrafficWorkload.Plo \
	workloads/traffic_mem/$(DEPDIR)/TrafficMemWorkload.Plo
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libSnnDL_la_SOURCES)
DIST_SOURCES = $(libSnnDL_la_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__extra_recursive_targets = snippets-recursive
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
am__DIST_COMMON = $(srcdir)/Makefile.in $(top_srcdir)/config/depcomp \
	README.md
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' aclocal-1.16
AMTAR = $${TAR-tar}
AM_CFLAGS =  
AM_CPPFLAGS =  -I/usr/include/python3.10 -I/usr/include/python3.10 -I/home/xgy/remote-20260430/remote/sst_install_mpi/include/sst/core -I/home/xgy/remote-20260430/remote/sst_install_mpi/include -I$(top_srcdir)/src -I$(srcdir) \
	-I$(srcdir)/api -I$(srcdir)/events -I$(srcdir)/components \
	-I$(srcdir)/platform/core -I$(srcdir)/snn/compute \
	-I$(srcdir)/snn/profiling -I$(SST_PREFIX)/include
AM_CXXFLAGS =  -std=c++17 
AM_DEFAULT_VERBOSITY = 0
AM_LDFLAGS =  -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lpython3.10 -lcrypt -ldl  -lm -lm 
AR = ar
ARIEL_MPICC = 
ARIEL_MPICXX = 
ARIEL_MPI_CFLAGS = 
ARIEL_MPI_LIBS = 
AUTOCONF = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' autoconf
AUTOHEADER = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' autoheader
AUTOMAKE = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' automake-1.16
AWK = gawk
CC = gcc
CCAS = gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g -O2
CCDEPMODE = depmode=gcc3
CC_VERSION = gcc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
CFLAGS = -g -O2
CPP = gcc
CPPFLAGS = 
CSCOPE = cscope
CTAGS = ctags
CUDA_CPPFLAGS = 
CUDA_LDFLAGS = 
CUDA_LIBDIR = 
CUDA_LIBS = 
CXX = g++ -std=c++17
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DRAMSIM3_CPPFLAGS = 
DRAMSIM3_LDFLAGS = 
DRAMSIM3_LIB = 
DRAMSIM3_LIBDIR = 
DRAMSIM_CPPFLAGS = 
DRAMSIM_LDFLAGS = 
DRAMSIM_LIB = 
DRAMSIM_LIBDIR = 
DSYMUTIL = 
DUMPBIN = 
DUMPI_CPPFLAGS = 
DUMPI_LDFLAGS = 
DUMPI_LIB = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
ETAGS = etags
EXEEXT = 
FDSIM_CPPFLAGS = 
FDSIM_CXXFLAGS = 
FDSIM_LDFLAGS = 
FDSIM_LIB = 
FDSIM_LIBDIR = 
FGREP = /usr/bin/grep -F
GOBLIN_HMCSIM_CPPFLAGS = 
GOBLIN_HMCSIM_LDFLAGS = 
GOBLIN_HMCSIM_LIB = 
GOBLIN_HMCSIM_LIBDIR = 
GPGPUSIM_CPPFLAGS = 
GPGPUSIM_LDFLAGS = 
GPGPUSIM_LIB = 
GPGPUSIM_LIBDIR = 
GREP = /usr/bin/grep
HAVE_SET_PTRACER = 1
HBMDRAMSIM_CPPFLAGS = 
HBMDRAMSIM_LDFLAGS = 
HBMDRAMSIM_LIB = 
HBMDRAMSIM_LIBDIR = 
HDF5_CPPFLAGS = 
HDF5_LDFLAGS = 
HDF5_LIBS = 
HYBRIDSIM_CPPFLAGS = 
HYBRIDSIM_LDFLAGS = 
HYBRIDSIM_LIB = 
HYBRIDSIM_LIBDIR = 
INCLTDL = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBADD_DL =  
LIBADD_DLD_LINK = 
LIBADD_DLOPEN = 
LIBADD_SHL_LOAD = 
LIBLTDL = -lltdl
LIBOBJS = 
LIBS =  
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBZ_CPPFLAGS = 
LIBZ_LDFLAGS = 
LIBZ_LIB = -lz
LIPO = 
LN_S = ln -s
LTDLDEPS = 
LTDLINCL = 
LTDLOPEN = libltdl
LTLIBOBJS = 
LT_ARGZ_H = 
LT_CONFIG_H = src/sst_element_config.h
LT_DLLOADERS =  dlopen.la
LT_DLPREOPEN = -dlpreopen dlopen.la 
LT_SYS_LIBRARY_PATH = 
MAKEINFO = ${SHELL} '/home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/missing' makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
MPICC = mpicc
MPICPP = 
MPICXX = mpic++
MPICXXCPP = 
MPILIBS = 
MPI_CPPFLAGS = 
NM = /usr/bin/nm -B
NMEDIT = 
NUMPY_CPPFLAGS = -I/home/xgy/.local/lib/python3.10/site-packages/numpy/_core/include -DHAVE_NUMPY
NVDIMMSIM_CPPFLAGS = 
NVDIMMSIM_CXXFLAGS = 
NVDIMMSIM_LDFLAGS = 
NVDIMMSIM_LIB = 
NVDIMMSIM_LIBDIR = 
OBJDUMP = objdump
OBJEXT = o
OTF2_CONFIG_TOOL = 
OTF2_CPPFLAGS = 
OTF2_LDFLAGS = 
OTF2_PATH = 
OTF_CONFIG_TOOL = 
OTF_CPPFLAGS = 
OTF_LDFLAGS = 
OTF_PATH = 
OTOOL = 
OTOOL64 = 
PACKAGE = sst-elements-library
PACKAGE_BUGREPORT = sst@sandia.gov
PACKAGE_NAME = SST Elements Library
PACKAGE_STRING = SST Elements Library 15.0.0
PACKAGE_TARNAME = sst-elements-library
PACKAGE_URL = 
PACKAGE_VERSION = 15.0.0
PATH_SEPARATOR = :
PINTOOL2_RUNTIME = 
PINTOOL3_RUNTIME = 
PINTOOL_CPPFLAGS = 
PINTOOL_DIR = 
PINTOOL_LDFLAGS = 
PINTOOL_PATH = /home/xgy/.codex/tmp/arg0/codex-arg0kfFNe2:/home/xgy/.nvm/versions/node/v22.20.0/lib/node_modules/@openai/codex/node_modules/@openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/path:/home/xgy/.local/bin:/usr/lib/jvm/java-17-openjdk-amd64/bin:/home/xgy/remote-20260430/remote/sst_install/bin:/home/xgy/remote-20260430/remote/sst_install/bin:/home/xgy/.nvm/versions/node/v22.20.0/bin:/home/xgy/.vscode-server/cli/servers/Stable-0f0d87fa9e96c856c5212fc86db137ac0d783365/server/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PINTOOL_RUNTIME = 
PIN_CPPFLAGS = -g   -Wall   -Werror   -Wno-unknown-pragmas   -D__PIN__=1 -DPIN_CRT=1   -fno-stack-protector   -fno-exceptions   -funwind-tables   -fasynchronous-unwind-tables   -fomit-frame-pointer   -fno-strict-aliasing   -fno-rtti   -faligned-new   -fpic   -DTARGET_IA32E   -DHOST_IA32E   -DTARGET_LINUX   -DPIN_VERSION_MINOR=
PIN_CPPFLAGS_COMPILER = -fno-exceptions          -fabi-version=2
RAMULATOR2_CPPFLAGS = -I/home/xgy/remote-20260430/remote/externals/ramulator2/src/ -I/home/xgy/remote-20260430/remote/externals/ramulator2/ext/spdlog/include/       -I/home/xgy/remote-20260430/remote/externals/ramulator2/ext/yaml-cpp/include/ -DRAMULATOR2 -DHAVE_RAMULATOR2
RAMULATOR2_LDFLAGS = -L/home/xgy/remote-20260430/remote/externals/ramulator2
RAMULATOR2_LIB = -lramulator
RAMULATOR2_LIBDIR = /home/xgy/remote-20260430/remote/externals/ramulator2
RAMULATOR_CPPFLAGS = 
RAMULATOR_LDFLAGS = 
RAMULATOR_LIB = 
RAMULATOR_LIBDIR = 
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/bash
SHM_LIB =  
SSTELEMENTS_GIT_BRANCH = snndl_re
SSTELEMENTS_GIT_COMMITCOUNT = 15405
SSTELEMENTS_GIT_HEADSHA = f30efc3539d21fb2076b762e6524113bf9d3a159
SST_ACTIVE_ELEMENT_LIBRARIES =  ariel cacheTracer cassini cramSim ember firefly gensa golem hermes iris kingsley mask-mpi memHierarchy mercury merlin messier miranda mmu osseous prospero rdmaNic samba shogun simpleElementExample simpleSimulation SnnDL thornhill vanadis vaultsim zodiac
SST_CONFIG_TOOL = /home/xgy/remote-20260430/remote/sst_install_mpi/bin/sst-config
SST_DIST_ELEMENT_LIBRARIES =  ariel balar cacheTracer cassini cramSim ember firefly gensa golem hermes iris kingsley mask-mpi memHierarchy mercury merlin messier miranda mmu osseous prospero rdmaNic samba shogun simpleElementExample simpleSimulation SnnDL thornhill vanadis vaultsim zodiac
SST_PREFIX = /home/xgy/remote-20260430/remote/sst_install_mpi
SST_REGISTER_TOOL = /home/xgy/remote-20260430/remote/sst_install_mpi/bin/sst-register
SST_SNIPPETS_TOOL = /home/xgy/remote-20260430/remote/sst_install_mpi/bin/sst-snippets.py
STAKE_CPPFLAGS = 
STAKE_LDFLAGS = 
STAKE_LIB = 
STAKE_LIBDIR = 
STRIP = strip
VERSION = 15.0.0
abs_builddir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements/src/sst/elements/SnnDL
abs_srcdir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements/src/sst/elements/SnnDL
abs_top_builddir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements
abs_top_srcdir = /home/xgy/remote-20260430/remote/sst_workspace/sst-elements
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=posix -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/xgy/remote-20260430/remote/sst_workspace/sst-elements/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
ltdl_LIBOBJS =  lt__strl.o
ltdl_LTLIBOBJS =  lt__strl.lo
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/xgy/remote-20260430/remote/sst_install_mpi
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sst_check_numpy_happy = yes
sys_symbol_underscore = no
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../../../
top_builddir = ../../../..
top_srcdir = ../../../..

# 可选的MPI支持 - 不影响现有构建
# 暂时注释掉，等待configure.ac配置完成
# if SST_CONFIG_HAVE_MPI
# AM_CPPFLAGS += $(MPI_CPPFLAGS)
# endif
compdir = $(pkglibdir)
comp_LTLIBRARIES = libSnnDL.la
libSnnDL_la_SOURCES = \
	api/CoreShellAPI.h \
	api/SnnInterface.h \
	api/ISpikeTransport.h \
	api/INocTransport.h \
	api/GasOps.h \
	api/IGasCmdSender.h \
	api/IGasStageSink.h \
	api/IGasStepGate.h \
	api/IGlobalStepHooks.h \
	api/ICoreMemoryLink.h \
	api/IMemoryAccess.h \
	api/IDmaTaggedAccess.h \
	api/IDmaSchedulerProvider.h \
	api/ILocalStorageProvider.h \
	api/ICoreWorkload.h \
	api/ISnnAccelRuntimeServices.h \
	api/ISpikeWorkload.h \
	api/WorkloadConfig.h \
	api/CoreWorkloadFactory.h \
	api/ISynapseRoute.h \
	api/SynapseRouteBuildConfig.h \
	api/SnnWeightReader.h \
	api/IWeightReaderAdopter.h \
	api/SnnDLLogging.h \
	events/GatingDecisionEvent.h \
	events/GasStepBarrierEvent.h \
	events/SimpleTestEvent.cc \
	events/SimpleTestEvent.h \
	events/SpikeEvent.h \
	events/SpikeEventWrapper.cc \
	events/SpikeEventWrapper.h \
	events/SpikePacket.h \
	components/gas/GlobalGasStepController.cc \
	components/gas/GlobalGasStepController.h \
	components/CachelineFragmentMemIF.cc \
	components/CachelineFragmentMemIF.h \
	components/GatherBufferIF.cc \
	components/GatherBufferIF.h \
	components/gather/GatherBufferIFConfig.cc \
	components/gather/GatherBufferIFConfig.h \
	components/GatingPE.cc \
	components/GatingPE.h \
	components/MemKCalBench.cc \
	components/MemKCalBench.h \
	components/multicore/MultiCorePEConfig.cc \
	components/multicore/MultiCorePEConfig.h \
	components/multicore/MultiCorePEObservability.cc \
	components/MultiCorePE.cc \
	components/MultiCorePE.h \
	components/SnnNIC.cc \
	components/SnnNIC.h \
	components/stimulus/SpikeSource.cc \
	components/stimulus/SpikeSource.h \
	components/WeightLoader.cc \
	components/WeightLoader.h \
	platform/stats/IWorkloadStatsModule.h \
	platform/stats/KeyedCounterStatsModule.h \
	platform/stats/StreamWorkloadStatsModule.h \
	platform/stats/TensorWorkloadStatsModule.h \
	platform/stats/WorkloadStatsRegistry.cc \
	platform/stats/WorkloadStatsRegistry.h \
	platform/core/SnnPESubComponent.cc \
	platform/core/SnnPESubComponentStats.cc \
	platform/core/SnnPESubComponent.h \
	platform/core/SnnPESubComponent_impl.h \
	platform/core/SnnPESubComponent_bcsr.cc \
	platform/core/SnnPESubComponent_routing.cc \
	platform/core/SnnPEApplyScatter.cc \
	platform/core/SnnPEOrchestrators.cc \
	snn/compute/SnnComputeCore.cc \
	snn/compute/SnnComputeCore.h \
	snn/compute/SnnCoreEngine.cc \
	snn/compute/SnnCoreEngine.h \
	snn/compute/SnnLearningCore.cc \
	snn/compute/SnnLearningCore.h \
	snn/compute/IWeightAwareComputeCore.h \
	snn/compute/SnnNeuronModel.h \
	snn/compute/SynapseManager.h \
	snn/synapse/gas/AccumulatorOps.cc \
	snn/synapse/gas/AccumulatorOps.h \
	snn/synapse/gas/GasCustomCmd.h \
	snn/synapse/gas/GasEdgeCollector.cc \
	snn/synapse/gas/GasEdgeCollector.h \
	snn/synapse/gas/GasPhaseController.cc \
	snn/synapse/gas/GasPhaseController.h \
	snn/synapse/stdmem/StdMemEndpoint.cc \
	snn/synapse/stdmem/StdMemEndpoint.h \
	snn/synapse/stdmem/SnnPESubComponent_mem.cc \
	platform/noc/OptimizedInternalRing.cc \
	platform/noc/OptimizedInternalRing.h \
	components/noc/SimpleNetworkWrapper.cc \
	components/noc/SimpleNetworkWrapper.h \
	snn/synapse/weights/SnnBcsrWeightManager.cc \
	snn/synapse/weights/SnnBcsrWeightManager.h \
	snn/synapse/weights/SnnWeightDiagnostics.cc \
	snn/synapse/weights/SnnWeightDiagnostics.h \
	components/noc/SnnNetworkAdapter.cc \
	components/noc/SnnNetworkAdapter.h \
	components/noc/MulticastRouter.cc \
	components/noc/MulticastRouter.h \
	research/noc3d/MulticastRouter3DNative.cc \
	research/noc3d/MulticastRouter3DNative.h \
	research/noc3d/MulticastRouter3DNativeConfig.h \
	research/noc3d/Noc3DSmokeSource.cc \
	research/noc3d/Noc3DSmokeSource.h \
	research/noc3d/Noc3DSmokeSink.cc \
	research/noc3d/Noc3DSmokeSink.h \
	research/noc3d/HBMStackStub.cc \
	research/noc3d/HBMStackStub.h \
	components/noc/MulticastNIC.cc \
	components/noc/MulticastNIC.h \
	snn/profiling/SnnProfiler.h \
	snn/synapse/route/SnnRouteProvider.cc \
	snn/synapse/route/SnnRouteProvider.h \
	snn/synapse/route/SpikeNocCodec.cc \
	snn/synapse/route/SpikeNocCodec.h \
	snn/synapse/route/BcsrRouteBuilder.cc \
	snn/synapse/route/BcsrRouteBuilder.h \
	snn/synapse/route/StepBcsrReachability.cc \
	snn/synapse/route/StepBcsrReachability.h \
	snn/synapse/route/SynapseRouteSubsystem.cc \
	snn/synapse/route/SynapseRouteSubsystem.h \
	research/route3d/Route3DNodeMapper.h \
	research/route3d/SynapseRouteSubsystem3D.cc \
	research/route3d/SynapseRouteSubsystem3D.h \
	snn/stimulus/StepActivationSubsystem.cc \
	snn/stimulus/StepActivationSubsystem.h \
	snn/stimulus/ExternalSpikeInputSubsystem.cc \
	snn/stimulus/ExternalSpikeInputSubsystem.h \
	platform/noc/NocSubsystem.cc \
	platform/noc/NocSubsystem.h \
	snn/synapse/weights/WeightAccessor.cc \
	snn/synapse/weights/WeightAccessor.h \
	snn/synapse/weights/WeightCacheOps.cc \
	snn/synapse/weights/WeightCacheOps.h \
	snn/synapse/weights/WeightMemorySubsystem.cc \
	snn/synapse/weights/WeightMemorySubsystemVerification.cc \
	snn/synapse/weights/WeightMemorySubsystem.h \
	snn/synapse/route/SpikeCommSubsystem.cc \
	snn/synapse/route/SpikeCommSubsystem.h \
	snn/synapse/route/SpikePacketTransport.h \
	snn/synapse/route/SpikePacketBridge.cc \
	snn/synapse/route/SpikePacketBridge.h \
	workloads/CoreWorkloadFactory.cc \
	workloads/common/SnnAccelBackend.cc \
	workloads/common/SnnAccelBackend.h \
	workloads/common/SnnAccelBackendContract.h \
	workloads/layout/NormalizedNeuronLayout.cc \
	workloads/layout/NormalizedNeuronLayout.h \
	workloads/riscv_snn/RiscvSnnAbi.h \
	workloads/riscv_snn/RiscvSnnAsm.h \
	workloads/riscv_snn/RiscvSnnBootDriver.cc \
	workloads/riscv_snn/RiscvSnnBootDriver.h \
	workloads/riscv_snn/RiscvSnnElfWriter.h \
	workloads/riscv_snn/RiscvSnnFirmwareLoader.cc \
	workloads/riscv_snn/RiscvSnnFirmwareLoader.h \
	workloads/riscv_snn/RiscvSnnHart.cc \
	workloads/riscv_snn/RiscvSnnHart.h \
	workloads/riscv_snn/RiscvSnnIss.cc \
	workloads/riscv_snn/RiscvSnnIss.h \
	workloads/riscv_snn/RiscvSnnMemoryImage.h \
	workloads/riscv_snn/RiscvSnnQueueContract.h \
	workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.cc \
	workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.h \
	workloads/riscv_snn/RiscvSnnSampleFirmware.h \
	workloads/riscv_snn/RiscvSnnShadowTransportExport.cc \
	workloads/riscv_snn/RiscvSnnShadowTransportExport.h \
	workloads/riscv_snn/RiscvSnnShadowRuntimeServices.cc \
	workloads/riscv_snn/RiscvSnnShadowRuntimeServices.h \
	workloads/riscv_snn/RiscvSnnWorkload.cc \
	workloads/riscv_snn/RiscvSnnWorkload.h \
	workloads/snn/SnnWorkload.cc \
	workloads/snn/SnnWorkload.h \
	workloads/stream/StreamWorkload.cc \
	workloads/stream/StreamWorkload.h \
	workloads/traffic/TrafficWorkload.cc \
	workloads/traffic/TrafficWorkload.h \
	workloads/traffic_mem/TrafficMemWorkload.cc \
	workloads/traffic_mem/TrafficMemWorkload.h \
	workloads/tensor/TensorWorkload.cc \
	workloads/tensor/TensorWorkloadCollective.cc \
	workloads/tensor/TensorWorkloadConfig.cc \
	workloads/tensor/TensorWorkloadProgram.cc \
	workloads/tensor/TensorWorkloadStats.cc \
	workloads/tensor/TensorWorkload.h \
	platform/memory/sram_sim/layout/VirtualSramLayout.h \
	platform/memory/sram_sim/model/BankedSramModel.cc \
	platform/memory/sram_sim/model/BankedSramModel.h \
	research/local_storage/LocalStorageTypes.h \
	research/local_storage/LocalStorageHierarchyController.cc \
	research/local_storage/LocalStorageHierarchyController.h \
	research/local_storage/PeWeightObjectPlane.cc \
	research/local_storage/PeWeightObjectPlane.h \
	platform/memory/DmaMemAccessProxy.cc \
	platform/memory/DmaMemAccessProxy.h \
	platform/memory/PeDmaScheduler.cc \
	platform/memory/PeDmaScheduler.h \
	platform/memory/StandardMemAccess.cc \
	platform/memory/StandardMemAccess.h


#
# Note: sources above include the production runtime and explicitly selected research modules.
#
libSnnDL_la_LDFLAGS = -module -avoid-version
RISCV_SNN_TEST_LINK = $(CXXLD) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(CXXFLAGS)
all: all-am

.SUFFIXES:
.SUFFIXES: .cc .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign src/sst/elements/SnnDL/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign src/sst/elements/SnnDL/Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

install-compLTLIBRARIES: $(comp_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(comp_LTLIBRARIES)'; test -n "$(compdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(compdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(compdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(compdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(compdir)"; \
	}

uninstall-compLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(comp_LTLIBRARIES)'; test -n "$(compdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(compdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(compdir)/$$f"; \
	done

clean-compLTLIBRARIES:
	-test -z "$(comp_LTLIBRARIES)" || rm -f $(comp_LTLIBRARIES)
	@list='$(comp_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
events/$(am__dirstamp):
	@$(MKDIR_P) events
	@: > events/$(am__dirstamp)
events/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) events/$(DEPDIR)
	@: > events/$(DEPDIR)/$(am__dirstamp)
events/SimpleTestEvent.lo: events/$(am__dirstamp) \
	events/$(DEPDIR)/$(am__dirstamp)
events/SpikeEventWrapper.lo: events/$(am__dirstamp) \
	events/$(DEPDIR)/$(am__dirstamp)
components/gas/$(am__dirstamp):
	@$(MKDIR_P) components/gas
	@: > components/gas/$(am__dirstamp)
components/gas/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/gas/$(DEPDIR)
	@: > components/gas/$(DEPDIR)/$(am__dirstamp)
components/gas/GlobalGasStepController.lo:  \
	components/gas/$(am__dirstamp) \
	components/gas/$(DEPDIR)/$(am__dirstamp)
components/$(am__dirstamp):
	@$(MKDIR_P) components
	@: > components/$(am__dirstamp)
components/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/$(DEPDIR)
	@: > components/$(DEPDIR)/$(am__dirstamp)
components/CachelineFragmentMemIF.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/GatherBufferIF.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/gather/$(am__dirstamp):
	@$(MKDIR_P) components/gather
	@: > components/gather/$(am__dirstamp)
components/gather/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/gather/$(DEPDIR)
	@: > components/gather/$(DEPDIR)/$(am__dirstamp)
components/gather/GatherBufferIFConfig.lo:  \
	components/gather/$(am__dirstamp) \
	components/gather/$(DEPDIR)/$(am__dirstamp)
components/gather/apply/$(am__dirstamp):
	@$(MKDIR_P) components/gather/apply
	@: > components/gather/apply/$(am__dirstamp)
components/gather/apply/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/gather/apply/$(DEPDIR)
	@: > components/gather/apply/$(DEPDIR)/$(am__dirstamp)
components/GatingPE.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/MemKCalBench.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/multicore/$(am__dirstamp):
	@$(MKDIR_P) components/multicore
	@: > components/multicore/$(am__dirstamp)
components/multicore/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/multicore/$(DEPDIR)
	@: > components/multicore/$(DEPDIR)/$(am__dirstamp)
components/multicore/MultiCorePEConfig.lo:  \
	components/multicore/$(am__dirstamp) \
	components/multicore/$(DEPDIR)/$(am__dirstamp)
components/multicore/MultiCorePEObservability.lo:  \
	components/multicore/$(am__dirstamp) \
	components/multicore/$(DEPDIR)/$(am__dirstamp)
components/MultiCorePE.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/SnnNIC.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
components/stimulus/$(am__dirstamp):
	@$(MKDIR_P) components/stimulus
	@: > components/stimulus/$(am__dirstamp)
components/stimulus/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/stimulus/$(DEPDIR)
	@: > components/stimulus/$(DEPDIR)/$(am__dirstamp)
components/stimulus/SpikeSource.lo:  \
	components/stimulus/$(am__dirstamp) \
	components/stimulus/$(DEPDIR)/$(am__dirstamp)
components/WeightLoader.lo: components/$(am__dirstamp) \
	components/$(DEPDIR)/$(am__dirstamp)
platform/stats/$(am__dirstamp):
	@$(MKDIR_P) platform/stats
	@: > platform/stats/$(am__dirstamp)
platform/stats/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/stats/$(DEPDIR)
	@: > platform/stats/$(DEPDIR)/$(am__dirstamp)
platform/stats/WorkloadStatsRegistry.lo:  \
	platform/stats/$(am__dirstamp) \
	platform/stats/$(DEPDIR)/$(am__dirstamp)
platform/core/$(am__dirstamp):
	@$(MKDIR_P) platform/core
	@: > platform/core/$(am__dirstamp)
platform/core/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/core/$(DEPDIR)
	@: > platform/core/$(DEPDIR)/$(am__dirstamp)
platform/core/SnnPESubComponent.lo: platform/core/$(am__dirstamp) \
	platform/core/$(DEPDIR)/$(am__dirstamp)
platform/core/SnnPESubComponentStats.lo:  \
	platform/core/$(am__dirstamp) \
	platform/core/$(DEPDIR)/$(am__dirstamp)
platform/core/SnnPESubComponent_bcsr.lo:  \
	platform/core/$(am__dirstamp) \
	platform/core/$(DEPDIR)/$(am__dirstamp)
platform/core/SnnPESubComponent_routing.lo:  \
	platform/core/$(am__dirstamp) \
	platform/core/$(DEPDIR)/$(am__dirstamp)
platform/core/SnnPEApplyScatter.lo: platform/core/$(am__dirstamp) \
	platform/core/$(DEPDIR)/$(am__dirstamp)
platform/core/SnnPEOrchestrators.lo: platform/core/$(am__dirstamp) \
	platform/core/$(DEPDIR)/$(am__dirstamp)
snn/compute/$(am__dirstamp):
	@$(MKDIR_P) snn/compute
	@: > snn/compute/$(am__dirstamp)
snn/compute/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/compute/$(DEPDIR)
	@: > snn/compute/$(DEPDIR)/$(am__dirstamp)
snn/compute/SnnComputeCore.lo: snn/compute/$(am__dirstamp) \
	snn/compute/$(DEPDIR)/$(am__dirstamp)
snn/compute/SnnCoreEngine.lo: snn/compute/$(am__dirstamp) \
	snn/compute/$(DEPDIR)/$(am__dirstamp)
snn/compute/SnnLearningCore.lo: snn/compute/$(am__dirstamp) \
	snn/compute/$(DEPDIR)/$(am__dirstamp)
snn/synapse/gas/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/gas
	@: > snn/synapse/gas/$(am__dirstamp)
snn/synapse/gas/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/gas/$(DEPDIR)
	@: > snn/synapse/gas/$(DEPDIR)/$(am__dirstamp)
snn/synapse/gas/AccumulatorOps.lo: snn/synapse/gas/$(am__dirstamp) \
	snn/synapse/gas/$(DEPDIR)/$(am__dirstamp)
snn/synapse/gas/GasEdgeCollector.lo: snn/synapse/gas/$(am__dirstamp) \
	snn/synapse/gas/$(DEPDIR)/$(am__dirstamp)
snn/synapse/gas/GasPhaseController.lo:  \
	snn/synapse/gas/$(am__dirstamp) \
	snn/synapse/gas/$(DEPDIR)/$(am__dirstamp)
snn/synapse/stdmem/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/stdmem
	@: > snn/synapse/stdmem/$(am__dirstamp)
snn/synapse/stdmem/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/stdmem/$(DEPDIR)
	@: > snn/synapse/stdmem/$(DEPDIR)/$(am__dirstamp)
snn/synapse/stdmem/StdMemEndpoint.lo:  \
	snn/synapse/stdmem/$(am__dirstamp) \
	snn/synapse/stdmem/$(DEPDIR)/$(am__dirstamp)
snn/synapse/stdmem/SnnPESubComponent_mem.lo:  \
	snn/synapse/stdmem/$(am__dirstamp) \
	snn/synapse/stdmem/$(DEPDIR)/$(am__dirstamp)
platform/noc/$(am__dirstamp):
	@$(MKDIR_P) platform/noc
	@: > platform/noc/$(am__dirstamp)
platform/noc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/noc/$(DEPDIR)
	@: > platform/noc/$(DEPDIR)/$(am__dirstamp)
platform/noc/OptimizedInternalRing.lo: platform/noc/$(am__dirstamp) \
	platform/noc/$(DEPDIR)/$(am__dirstamp)
components/noc/$(am__dirstamp):
	@$(MKDIR_P) components/noc
	@: > components/noc/$(am__dirstamp)
components/noc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) components/noc/$(DEPDIR)
	@: > components/noc/$(DEPDIR)/$(am__dirstamp)
components/noc/SimpleNetworkWrapper.lo:  \
	components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
snn/synapse/weights/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/weights
	@: > snn/synapse/weights/$(am__dirstamp)
snn/synapse/weights/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/weights/$(DEPDIR)
	@: > snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
snn/synapse/weights/SnnBcsrWeightManager.lo:  \
	snn/synapse/weights/$(am__dirstamp) \
	snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
snn/synapse/weights/SnnWeightDiagnostics.lo:  \
	snn/synapse/weights/$(am__dirstamp) \
	snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
components/noc/SnnNetworkAdapter.lo: components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
components/noc/MulticastRouter.lo: components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
research/noc3d/$(am__dirstamp):
	@$(MKDIR_P) research/noc3d
	@: > research/noc3d/$(am__dirstamp)
research/noc3d/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) research/noc3d/$(DEPDIR)
	@: > research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/MulticastRouter3DNative.lo:  \
	research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/Noc3DSmokeSource.lo: research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/Noc3DSmokeSink.lo: research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
research/noc3d/HBMStackStub.lo: research/noc3d/$(am__dirstamp) \
	research/noc3d/$(DEPDIR)/$(am__dirstamp)
components/noc/MulticastNIC.lo: components/noc/$(am__dirstamp) \
	components/noc/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/route
	@: > snn/synapse/route/$(am__dirstamp)
snn/synapse/route/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/synapse/route/$(DEPDIR)
	@: > snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SnnRouteProvider.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SpikeNocCodec.lo: snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/BcsrRouteBuilder.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/StepBcsrReachability.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SynapseRouteSubsystem.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
research/route3d/$(am__dirstamp):
	@$(MKDIR_P) research/route3d
	@: > research/route3d/$(am__dirstamp)
research/route3d/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) research/route3d/$(DEPDIR)
	@: > research/route3d/$(DEPDIR)/$(am__dirstamp)
research/route3d/SynapseRouteSubsystem3D.lo:  \
	research/route3d/$(am__dirstamp) \
	research/route3d/$(DEPDIR)/$(am__dirstamp)
snn/stimulus/$(am__dirstamp):
	@$(MKDIR_P) snn/stimulus
	@: > snn/stimulus/$(am__dirstamp)
snn/stimulus/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) snn/stimulus/$(DEPDIR)
	@: > snn/stimulus/$(DEPDIR)/$(am__dirstamp)
snn/stimulus/StepActivationSubsystem.lo: snn/stimulus/$(am__dirstamp) \
	snn/stimulus/$(DEPDIR)/$(am__dirstamp)
snn/stimulus/ExternalSpikeInputSubsystem.lo:  \
	snn/stimulus/$(am__dirstamp) \
	snn/stimulus/$(DEPDIR)/$(am__dirstamp)
platform/noc/NocSubsystem.lo: platform/noc/$(am__dirstamp) \
	platform/noc/$(DEPDIR)/$(am__dirstamp)
snn/synapse/weights/WeightAccessor.lo:  \
	snn/synapse/weights/$(am__dirstamp) \
	snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
snn/synapse/weights/WeightCacheOps.lo:  \
	snn/synapse/weights/$(am__dirstamp) \
	snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
snn/synapse/weights/WeightMemorySubsystem.lo:  \
	snn/synapse/weights/$(am__dirstamp) \
	snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
snn/synapse/weights/WeightMemorySubsystemVerification.lo:  \
	snn/synapse/weights/$(am__dirstamp) \
	snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SpikeCommSubsystem.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
snn/synapse/route/SpikePacketBridge.lo:  \
	snn/synapse/route/$(am__dirstamp) \
	snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
workloads/$(am__dirstamp):
	@$(MKDIR_P) workloads
	@: > workloads/$(am__dirstamp)
workloads/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/$(DEPDIR)
	@: > workloads/$(DEPDIR)/$(am__dirstamp)
workloads/CoreWorkloadFactory.lo: workloads/$(am__dirstamp) \
	workloads/$(DEPDIR)/$(am__dirstamp)
workloads/common/$(am__dirstamp):
	@$(MKDIR_P) workloads/common
	@: > workloads/common/$(am__dirstamp)
workloads/common/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/common/$(DEPDIR)
	@: > workloads/common/$(DEPDIR)/$(am__dirstamp)
workloads/common/SnnAccelBackend.lo: workloads/common/$(am__dirstamp) \
	workloads/common/$(DEPDIR)/$(am__dirstamp)
workloads/layout/$(am__dirstamp):
	@$(MKDIR_P) workloads/layout
	@: > workloads/layout/$(am__dirstamp)
workloads/layout/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/layout/$(DEPDIR)
	@: > workloads/layout/$(DEPDIR)/$(am__dirstamp)
workloads/layout/NormalizedNeuronLayout.lo:  \
	workloads/layout/$(am__dirstamp) \
	workloads/layout/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/$(am__dirstamp):
	@$(MKDIR_P) workloads/riscv_snn
	@: > workloads/riscv_snn/$(am__dirstamp)
workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/riscv_snn/$(DEPDIR)
	@: > workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnBootDriver.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnFirmwareLoader.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnHart.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnIss.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnShadowTransportExport.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnShadowRuntimeServices.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/riscv_snn/RiscvSnnWorkload.lo:  \
	workloads/riscv_snn/$(am__dirstamp) \
	workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
workloads/snn/$(am__dirstamp):
	@$(MKDIR_P) workloads/snn
	@: > workloads/snn/$(am__dirstamp)
workloads/snn/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/snn/$(DEPDIR)
	@: > workloads/snn/$(DEPDIR)/$(am__dirstamp)
workloads/snn/SnnWorkload.lo: workloads/snn/$(am__dirstamp) \
	workloads/snn/$(DEPDIR)/$(am__dirstamp)
workloads/stream/$(am__dirstamp):
	@$(MKDIR_P) workloads/stream
	@: > workloads/stream/$(am__dirstamp)
workloads/stream/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/stream/$(DEPDIR)
	@: > workloads/stream/$(DEPDIR)/$(am__dirstamp)
workloads/stream/StreamWorkload.lo: workloads/stream/$(am__dirstamp) \
	workloads/stream/$(DEPDIR)/$(am__dirstamp)
workloads/traffic/$(am__dirstamp):
	@$(MKDIR_P) workloads/traffic
	@: > workloads/traffic/$(am__dirstamp)
workloads/traffic/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/traffic/$(DEPDIR)
	@: > workloads/traffic/$(DEPDIR)/$(am__dirstamp)
workloads/traffic/TrafficWorkload.lo:  \
	workloads/traffic/$(am__dirstamp) \
	workloads/traffic/$(DEPDIR)/$(am__dirstamp)
workloads/traffic_mem/$(am__dirstamp):
	@$(MKDIR_P) workloads/traffic_mem
	@: > workloads/traffic_mem/$(am__dirstamp)
workloads/traffic_mem/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/traffic_mem/$(DEPDIR)
	@: > workloads/traffic_mem/$(DEPDIR)/$(am__dirstamp)
workloads/traffic_mem/TrafficMemWorkload.lo:  \
	workloads/traffic_mem/$(am__dirstamp) \
	workloads/traffic_mem/$(DEPDIR)/$(am__dirstamp)
workloads/tensor/$(am__dirstamp):
	@$(MKDIR_P) workloads/tensor
	@: > workloads/tensor/$(am__dirstamp)
workloads/tensor/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) workloads/tensor/$(DEPDIR)
	@: > workloads/tensor/$(DEPDIR)/$(am__dirstamp)
workloads/tensor/TensorWorkload.lo: workloads/tensor/$(am__dirstamp) \
	workloads/tensor/$(DEPDIR)/$(am__dirstamp)
workloads/tensor/TensorWorkloadCollective.lo:  \
	workloads/tensor/$(am__dirstamp) \
	workloads/tensor/$(DEPDIR)/$(am__dirstamp)
workloads/tensor/TensorWorkloadConfig.lo:  \
	workloads/tensor/$(am__dirstamp) \
	workloads/tensor/$(DEPDIR)/$(am__dirstamp)
workloads/tensor/TensorWorkloadProgram.lo:  \
	workloads/tensor/$(am__dirstamp) \
	workloads/tensor/$(DEPDIR)/$(am__dirstamp)
workloads/tensor/TensorWorkloadStats.lo:  \
	workloads/tensor/$(am__dirstamp) \
	workloads/tensor/$(DEPDIR)/$(am__dirstamp)
platform/memory/sram_sim/model/$(am__dirstamp):
	@$(MKDIR_P) platform/memory/sram_sim/model
	@: > platform/memory/sram_sim/model/$(am__dirstamp)
platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/memory/sram_sim/model/$(DEPDIR)
	@: > platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp)
platform/memory/sram_sim/model/BankedSramModel.lo:  \
	platform/memory/sram_sim/model/$(am__dirstamp) \
	platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp)
research/local_storage/$(am__dirstamp):
	@$(MKDIR_P) research/local_storage
	@: > research/local_storage/$(am__dirstamp)
research/local_storage/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) research/local_storage/$(DEPDIR)
	@: > research/local_storage/$(DEPDIR)/$(am__dirstamp)
research/local_storage/LocalStorageHierarchyController.lo:  \
	research/local_storage/$(am__dirstamp) \
	research/local_storage/$(DEPDIR)/$(am__dirstamp)
research/local_storage/PeWeightObjectPlane.lo:  \
	research/local_storage/$(am__dirstamp) \
	research/local_storage/$(DEPDIR)/$(am__dirstamp)
platform/memory/$(am__dirstamp):
	@$(MKDIR_P) platform/memory
	@: > platform/memory/$(am__dirstamp)
platform/memory/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) platform/memory/$(DEPDIR)
	@: > platform/memory/$(DEPDIR)/$(am__dirstamp)
platform/memory/DmaMemAccessProxy.lo: platform/memory/$(am__dirstamp) \
	platform/memory/$(DEPDIR)/$(am__dirstamp)
research/pe_fabric/$(am__dirstamp):
	@$(MKDIR_P) research/pe_fabric
	@: > research/pe_fabric/$(am__dirstamp)
research/pe_fabric/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) research/pe_fabric/$(DEPDIR)
	@: > research/pe_fabric/$(DEPDIR)/$(am__dirstamp)
platform/memory/PeDmaScheduler.lo: platform/memory/$(am__dirstamp) \
	platform/memory/$(DEPDIR)/$(am__dirstamp)
platform/memory/StandardMemAccess.lo: platform/memory/$(am__dirstamp) \
	platform/memory/$(DEPDIR)/$(am__dirstamp)

libSnnDL.la: $(libSnnDL_la_OBJECTS) $(libSnnDL_la_DEPENDENCIES) $(EXTRA_libSnnDL_la_DEPENDENCIES) 
	$(AM_V_CXXLD)$(libSnnDL_la_LINK) -rpath $(compdir) $(libSnnDL_la_OBJECTS) $(libSnnDL_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f components/*.$(OBJEXT)
	-rm -f components/*.lo
	-rm -f components/gas/*.$(OBJEXT)
	-rm -f components/gas/*.lo
	-rm -f components/gather/*.$(OBJEXT)
	-rm -f components/gather/*.lo
	-rm -f components/gather/apply/*.$(OBJEXT)
	-rm -f components/gather/apply/*.lo
	-rm -f components/multicore/*.$(OBJEXT)
	-rm -f components/multicore/*.lo
	-rm -f components/noc/*.$(OBJEXT)
	-rm -f components/noc/*.lo
	-rm -f components/stimulus/*.$(OBJEXT)
	-rm -f components/stimulus/*.lo
	-rm -f events/*.$(OBJEXT)
	-rm -f events/*.lo
	-rm -f platform/core/*.$(OBJEXT)
	-rm -f platform/core/*.lo
	-rm -f platform/memory/*.$(OBJEXT)
	-rm -f platform/memory/*.lo
	-rm -f platform/memory/sram_sim/model/*.$(OBJEXT)
	-rm -f platform/memory/sram_sim/model/*.lo
	-rm -f platform/noc/*.$(OBJEXT)
	-rm -f platform/noc/*.lo
	-rm -f platform/stats/*.$(OBJEXT)
	-rm -f platform/stats/*.lo
	-rm -f research/local_storage/*.$(OBJEXT)
	-rm -f research/local_storage/*.lo
	-rm -f research/noc3d/*.$(OBJEXT)
	-rm -f research/noc3d/*.lo
	-rm -f research/pe_fabric/*.$(OBJEXT)
	-rm -f research/pe_fabric/*.lo
	-rm -f research/route3d/*.$(OBJEXT)
	-rm -f research/route3d/*.lo
	-rm -f snn/compute/*.$(OBJEXT)
	-rm -f snn/compute/*.lo
	-rm -f snn/stimulus/*.$(OBJEXT)
	-rm -f snn/stimulus/*.lo
	-rm -f snn/synapse/gas/*.$(OBJEXT)
	-rm -f snn/synapse/gas/*.lo
	-rm -f snn/synapse/route/*.$(OBJEXT)
	-rm -f snn/synapse/route/*.lo
	-rm -f snn/synapse/stdmem/*.$(OBJEXT)
	-rm -f snn/synapse/stdmem/*.lo
	-rm -f snn/synapse/weights/*.$(OBJEXT)
	-rm -f snn/synapse/weights/*.lo
	-rm -f workloads/*.$(OBJEXT)
	-rm -f workloads/*.lo
	-rm -f workloads/common/*.$(OBJEXT)
	-rm -f workloads/common/*.lo
	-rm -f workloads/layout/*.$(OBJEXT)
	-rm -f workloads/layout/*.lo
	-rm -f workloads/riscv_snn/*.$(OBJEXT)
	-rm -f workloads/riscv_snn/*.lo
	-rm -f workloads/snn/*.$(OBJEXT)
	-rm -f workloads/snn/*.lo
	-rm -f workloads/stream/*.$(OBJEXT)
	-rm -f workloads/stream/*.lo
	-rm -f workloads/tensor/*.$(OBJEXT)
	-rm -f workloads/tensor/*.lo
	-rm -f workloads/traffic/*.$(OBJEXT)
	-rm -f workloads/traffic/*.lo
	-rm -f workloads/traffic_mem/*.$(OBJEXT)
	-rm -f workloads/traffic_mem/*.lo

distclean-compile:
	-rm -f *.tab.c

include components/$(DEPDIR)/CachelineFragmentMemIF.Plo # am--include-marker
include components/$(DEPDIR)/GatherBufferIF.Plo # am--include-marker
include components/$(DEPDIR)/GatingPE.Plo # am--include-marker
include components/$(DEPDIR)/MemKCalBench.Plo # am--include-marker
include components/$(DEPDIR)/MultiCorePE.Plo # am--include-marker
include components/$(DEPDIR)/SnnNIC.Plo # am--include-marker
include components/$(DEPDIR)/WeightLoader.Plo # am--include-marker
include components/gas/$(DEPDIR)/GlobalGasStepController.Plo # am--include-marker
include components/gather/$(DEPDIR)/GatherBufferIFConfig.Plo # am--include-marker
include components/multicore/$(DEPDIR)/MultiCorePEConfig.Plo # am--include-marker
include components/multicore/$(DEPDIR)/MultiCorePEObservability.Plo # am--include-marker
include components/noc/$(DEPDIR)/MulticastNIC.Plo # am--include-marker
include components/noc/$(DEPDIR)/MulticastRouter.Plo # am--include-marker
include components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo # am--include-marker
include components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo # am--include-marker
include components/stimulus/$(DEPDIR)/SpikeSource.Plo # am--include-marker
include events/$(DEPDIR)/SimpleTestEvent.Plo # am--include-marker
include events/$(DEPDIR)/SpikeEventWrapper.Plo # am--include-marker
include platform/core/$(DEPDIR)/SnnPEApplyScatter.Plo # am--include-marker
include platform/core/$(DEPDIR)/SnnPEOrchestrators.Plo # am--include-marker
include platform/core/$(DEPDIR)/SnnPESubComponent.Plo # am--include-marker
include platform/core/$(DEPDIR)/SnnPESubComponentStats.Plo # am--include-marker
include platform/core/$(DEPDIR)/SnnPESubComponent_bcsr.Plo # am--include-marker
include platform/core/$(DEPDIR)/SnnPESubComponent_routing.Plo # am--include-marker
include platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo # am--include-marker
include platform/memory/$(DEPDIR)/PeDmaScheduler.Plo # am--include-marker
include platform/memory/$(DEPDIR)/StandardMemAccess.Plo # am--include-marker
include platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo # am--include-marker
include platform/noc/$(DEPDIR)/NocSubsystem.Plo # am--include-marker
include platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo # am--include-marker
include platform/stats/$(DEPDIR)/WorkloadStatsRegistry.Plo # am--include-marker
include research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo # am--include-marker
include research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/HBMStackStub.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo # am--include-marker
include research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo # am--include-marker
include research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo # am--include-marker
include snn/compute/$(DEPDIR)/SnnComputeCore.Plo # am--include-marker
include snn/compute/$(DEPDIR)/SnnCoreEngine.Plo # am--include-marker
include snn/compute/$(DEPDIR)/SnnLearningCore.Plo # am--include-marker
include snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo # am--include-marker
include snn/stimulus/$(DEPDIR)/StepActivationSubsystem.Plo # am--include-marker
include snn/synapse/gas/$(DEPDIR)/AccumulatorOps.Plo # am--include-marker
include snn/synapse/gas/$(DEPDIR)/GasEdgeCollector.Plo # am--include-marker
include snn/synapse/gas/$(DEPDIR)/GasPhaseController.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo # am--include-marker
include snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo # am--include-marker
include snn/synapse/stdmem/$(DEPDIR)/SnnPESubComponent_mem.Plo # am--include-marker
include snn/synapse/stdmem/$(DEPDIR)/StdMemEndpoint.Plo # am--include-marker
include snn/synapse/weights/$(DEPDIR)/SnnBcsrWeightManager.Plo # am--include-marker
include snn/synapse/weights/$(DEPDIR)/SnnWeightDiagnostics.Plo # am--include-marker
include snn/synapse/weights/$(DEPDIR)/WeightAccessor.Plo # am--include-marker
include snn/synapse/weights/$(DEPDIR)/WeightCacheOps.Plo # am--include-marker
include snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystem.Plo # am--include-marker
include snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystemVerification.Plo # am--include-marker
include workloads/$(DEPDIR)/CoreWorkloadFactory.Plo # am--include-marker
include workloads/common/$(DEPDIR)/SnnAccelBackend.Plo # am--include-marker
include workloads/layout/$(DEPDIR)/NormalizedNeuronLayout.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnBootDriver.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnFirmwareLoader.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnHart.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnIss.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnRuntimeBridgeBackend.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowRuntimeServices.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowTransportExport.Plo # am--include-marker
include workloads/riscv_snn/$(DEPDIR)/RiscvSnnWorkload.Plo # am--include-marker
include workloads/snn/$(DEPDIR)/SnnWorkload.Plo # am--include-marker
include workloads/stream/$(DEPDIR)/StreamWorkload.Plo # am--include-marker
include workloads/tensor/$(DEPDIR)/TensorWorkload.Plo # am--include-marker
include workloads/tensor/$(DEPDIR)/TensorWorkloadCollective.Plo # am--include-marker
include workloads/tensor/$(DEPDIR)/TensorWorkloadConfig.Plo # am--include-marker
include workloads/tensor/$(DEPDIR)/TensorWorkloadProgram.Plo # am--include-marker
include workloads/tensor/$(DEPDIR)/TensorWorkloadStats.Plo # am--include-marker
include workloads/traffic/$(DEPDIR)/TrafficWorkload.Plo # am--include-marker
include workloads/traffic_mem/$(DEPDIR)/TrafficMemWorkload.Plo # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.cc.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cc.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf components/.libs components/_libs
	-rm -rf components/gas/.libs components/gas/_libs
	-rm -rf components/gather/.libs components/gather/_libs
	-rm -rf components/gather/apply/.libs components/gather/apply/_libs
	-rm -rf components/multicore/.libs components/multicore/_libs
	-rm -rf components/noc/.libs components/noc/_libs
	-rm -rf components/stimulus/.libs components/stimulus/_libs
	-rm -rf events/.libs events/_libs
	-rm -rf platform/core/.libs platform/core/_libs
	-rm -rf platform/memory/.libs platform/memory/_libs
	-rm -rf platform/memory/sram_sim/model/.libs platform/memory/sram_sim/model/_libs
	-rm -rf platform/noc/.libs platform/noc/_libs
	-rm -rf platform/stats/.libs platform/stats/_libs
	-rm -rf research/local_storage/.libs research/local_storage/_libs
	-rm -rf research/noc3d/.libs research/noc3d/_libs
	-rm -rf research/pe_fabric/.libs research/pe_fabric/_libs
	-rm -rf research/route3d/.libs research/route3d/_libs
	-rm -rf snn/compute/.libs snn/compute/_libs
	-rm -rf snn/stimulus/.libs snn/stimulus/_libs
	-rm -rf snn/synapse/gas/.libs snn/synapse/gas/_libs
	-rm -rf snn/synapse/route/.libs snn/synapse/route/_libs
	-rm -rf snn/synapse/stdmem/.libs snn/synapse/stdmem/_libs
	-rm -rf snn/synapse/weights/.libs snn/synapse/weights/_libs
	-rm -rf workloads/.libs workloads/_libs
	-rm -rf workloads/common/.libs workloads/common/_libs
	-rm -rf workloads/layout/.libs workloads/layout/_libs
	-rm -rf workloads/riscv_snn/.libs workloads/riscv_snn/_libs
	-rm -rf workloads/snn/.libs workloads/snn/_libs
	-rm -rf workloads/stream/.libs workloads/stream/_libs
	-rm -rf workloads/tensor/.libs workloads/tensor/_libs
	-rm -rf workloads/traffic/.libs workloads/traffic/_libs
	-rm -rf workloads/traffic_mem/.libs workloads/traffic_mem/_libs
snippets-local: 

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES)
installdirs:
	for dir in "$(DESTDIR)$(compdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f components/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/$(am__dirstamp)
	-rm -f components/gas/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/gas/$(am__dirstamp)
	-rm -f components/gather/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/gather/$(am__dirstamp)
	-rm -f components/gather/apply/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/gather/apply/$(am__dirstamp)
	-rm -f components/multicore/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/multicore/$(am__dirstamp)
	-rm -f components/noc/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/noc/$(am__dirstamp)
	-rm -f components/stimulus/$(DEPDIR)/$(am__dirstamp)
	-rm -f components/stimulus/$(am__dirstamp)
	-rm -f events/$(DEPDIR)/$(am__dirstamp)
	-rm -f events/$(am__dirstamp)
	-rm -f platform/core/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/core/$(am__dirstamp)
	-rm -f platform/memory/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/memory/$(am__dirstamp)
	-rm -f platform/memory/sram_sim/model/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/memory/sram_sim/model/$(am__dirstamp)
	-rm -f platform/noc/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/noc/$(am__dirstamp)
	-rm -f platform/stats/$(DEPDIR)/$(am__dirstamp)
	-rm -f platform/stats/$(am__dirstamp)
	-rm -f research/local_storage/$(DEPDIR)/$(am__dirstamp)
	-rm -f research/local_storage/$(am__dirstamp)
	-rm -f research/noc3d/$(DEPDIR)/$(am__dirstamp)
	-rm -f research/noc3d/$(am__dirstamp)
	-rm -f research/pe_fabric/$(DEPDIR)/$(am__dirstamp)
	-rm -f research/pe_fabric/$(am__dirstamp)
	-rm -f research/route3d/$(DEPDIR)/$(am__dirstamp)
	-rm -f research/route3d/$(am__dirstamp)
	-rm -f snn/compute/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/compute/$(am__dirstamp)
	-rm -f snn/stimulus/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/stimulus/$(am__dirstamp)
	-rm -f snn/synapse/gas/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/synapse/gas/$(am__dirstamp)
	-rm -f snn/synapse/route/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/synapse/route/$(am__dirstamp)
	-rm -f snn/synapse/stdmem/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/synapse/stdmem/$(am__dirstamp)
	-rm -f snn/synapse/weights/$(DEPDIR)/$(am__dirstamp)
	-rm -f snn/synapse/weights/$(am__dirstamp)
	-rm -f workloads/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/$(am__dirstamp)
	-rm -f workloads/common/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/common/$(am__dirstamp)
	-rm -f workloads/layout/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/layout/$(am__dirstamp)
	-rm -f workloads/riscv_snn/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/riscv_snn/$(am__dirstamp)
	-rm -f workloads/snn/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/snn/$(am__dirstamp)
	-rm -f workloads/stream/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/stream/$(am__dirstamp)
	-rm -f workloads/tensor/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/tensor/$(am__dirstamp)
	-rm -f workloads/traffic/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/traffic/$(am__dirstamp)
	-rm -f workloads/traffic_mem/$(DEPDIR)/$(am__dirstamp)
	-rm -f workloads/traffic_mem/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-compLTLIBRARIES clean-generic clean-libtool \
	mostlyclean-am

distclean: distclean-am
		-rm -f components/$(DEPDIR)/CachelineFragmentMemIF.Plo
	-rm -f components/$(DEPDIR)/GatherBufferIF.Plo
	-rm -f components/$(DEPDIR)/GatingPE.Plo
	-rm -f components/$(DEPDIR)/MemKCalBench.Plo
	-rm -f components/$(DEPDIR)/MultiCorePE.Plo
	-rm -f components/$(DEPDIR)/SnnNIC.Plo
	-rm -f components/$(DEPDIR)/WeightLoader.Plo
	-rm -f components/gas/$(DEPDIR)/GlobalGasStepController.Plo
	-rm -f components/gather/$(DEPDIR)/GatherBufferIFConfig.Plo
	-rm -f components/multicore/$(DEPDIR)/MultiCorePEConfig.Plo
	-rm -f components/multicore/$(DEPDIR)/MultiCorePEObservability.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastNIC.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastRouter.Plo
	-rm -f components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo
	-rm -f components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo
	-rm -f components/stimulus/$(DEPDIR)/SpikeSource.Plo
	-rm -f events/$(DEPDIR)/SimpleTestEvent.Plo
	-rm -f events/$(DEPDIR)/SpikeEventWrapper.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPEApplyScatter.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPEOrchestrators.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponent.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponentStats.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponent_bcsr.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponent_routing.Plo
	-rm -f platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo
	-rm -f platform/memory/$(DEPDIR)/PeDmaScheduler.Plo
	-rm -f platform/memory/$(DEPDIR)/StandardMemAccess.Plo
	-rm -f platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo
	-rm -f platform/noc/$(DEPDIR)/NocSubsystem.Plo
	-rm -f platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo
	-rm -f platform/stats/$(DEPDIR)/WorkloadStatsRegistry.Plo
	-rm -f research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo
	-rm -f research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo
	-rm -f research/noc3d/$(DEPDIR)/HBMStackStub.Plo
	-rm -f research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo
	-rm -f research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnComputeCore.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnCoreEngine.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnLearningCore.Plo
	-rm -f snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo
	-rm -f snn/stimulus/$(DEPDIR)/StepActivationSubsystem.Plo
	-rm -f snn/synapse/gas/$(DEPDIR)/AccumulatorOps.Plo
	-rm -f snn/synapse/gas/$(DEPDIR)/GasEdgeCollector.Plo
	-rm -f snn/synapse/gas/$(DEPDIR)/GasPhaseController.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo
	-rm -f snn/synapse/stdmem/$(DEPDIR)/SnnPESubComponent_mem.Plo
	-rm -f snn/synapse/stdmem/$(DEPDIR)/StdMemEndpoint.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/SnnBcsrWeightManager.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/SnnWeightDiagnostics.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightAccessor.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightCacheOps.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystem.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystemVerification.Plo
	-rm -f workloads/$(DEPDIR)/CoreWorkloadFactory.Plo
	-rm -f workloads/common/$(DEPDIR)/SnnAccelBackend.Plo
	-rm -f workloads/layout/$(DEPDIR)/NormalizedNeuronLayout.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnBootDriver.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnFirmwareLoader.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnHart.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnIss.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnRuntimeBridgeBackend.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowRuntimeServices.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowTransportExport.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnWorkload.Plo
	-rm -f workloads/snn/$(DEPDIR)/SnnWorkload.Plo
	-rm -f workloads/stream/$(DEPDIR)/StreamWorkload.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkload.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadCollective.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadConfig.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadProgram.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadStats.Plo
	-rm -f workloads/traffic/$(DEPDIR)/TrafficWorkload.Plo
	-rm -f workloads/traffic_mem/$(DEPDIR)/TrafficMemWorkload.Plo
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-compLTLIBRARIES

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
		-rm -f components/$(DEPDIR)/CachelineFragmentMemIF.Plo
	-rm -f components/$(DEPDIR)/GatherBufferIF.Plo
	-rm -f components/$(DEPDIR)/GatingPE.Plo
	-rm -f components/$(DEPDIR)/MemKCalBench.Plo
	-rm -f components/$(DEPDIR)/MultiCorePE.Plo
	-rm -f components/$(DEPDIR)/SnnNIC.Plo
	-rm -f components/$(DEPDIR)/WeightLoader.Plo
	-rm -f components/gas/$(DEPDIR)/GlobalGasStepController.Plo
	-rm -f components/gather/$(DEPDIR)/GatherBufferIFConfig.Plo
	-rm -f components/multicore/$(DEPDIR)/MultiCorePEConfig.Plo
	-rm -f components/multicore/$(DEPDIR)/MultiCorePEObservability.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastNIC.Plo
	-rm -f components/noc/$(DEPDIR)/MulticastRouter.Plo
	-rm -f components/noc/$(DEPDIR)/SimpleNetworkWrapper.Plo
	-rm -f components/noc/$(DEPDIR)/SnnNetworkAdapter.Plo
	-rm -f components/stimulus/$(DEPDIR)/SpikeSource.Plo
	-rm -f events/$(DEPDIR)/SimpleTestEvent.Plo
	-rm -f events/$(DEPDIR)/SpikeEventWrapper.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPEApplyScatter.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPEOrchestrators.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponent.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponentStats.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponent_bcsr.Plo
	-rm -f platform/core/$(DEPDIR)/SnnPESubComponent_routing.Plo
	-rm -f platform/memory/$(DEPDIR)/DmaMemAccessProxy.Plo
	-rm -f platform/memory/$(DEPDIR)/PeDmaScheduler.Plo
	-rm -f platform/memory/$(DEPDIR)/StandardMemAccess.Plo
	-rm -f platform/memory/sram_sim/model/$(DEPDIR)/BankedSramModel.Plo
	-rm -f platform/noc/$(DEPDIR)/NocSubsystem.Plo
	-rm -f platform/noc/$(DEPDIR)/OptimizedInternalRing.Plo
	-rm -f platform/stats/$(DEPDIR)/WorkloadStatsRegistry.Plo
	-rm -f research/local_storage/$(DEPDIR)/LocalStorageHierarchyController.Plo
	-rm -f research/local_storage/$(DEPDIR)/PeWeightObjectPlane.Plo
	-rm -f research/noc3d/$(DEPDIR)/HBMStackStub.Plo
	-rm -f research/noc3d/$(DEPDIR)/MulticastRouter3DNative.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSink.Plo
	-rm -f research/noc3d/$(DEPDIR)/Noc3DSmokeSource.Plo
	-rm -f research/route3d/$(DEPDIR)/SynapseRouteSubsystem3D.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnComputeCore.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnCoreEngine.Plo
	-rm -f snn/compute/$(DEPDIR)/SnnLearningCore.Plo
	-rm -f snn/stimulus/$(DEPDIR)/ExternalSpikeInputSubsystem.Plo
	-rm -f snn/stimulus/$(DEPDIR)/StepActivationSubsystem.Plo
	-rm -f snn/synapse/gas/$(DEPDIR)/AccumulatorOps.Plo
	-rm -f snn/synapse/gas/$(DEPDIR)/GasEdgeCollector.Plo
	-rm -f snn/synapse/gas/$(DEPDIR)/GasPhaseController.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/BcsrRouteBuilder.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SnnRouteProvider.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeCommSubsystem.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikeNocCodec.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SpikePacketBridge.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/StepBcsrReachability.Plo
	-rm -f snn/synapse/route/$(DEPDIR)/SynapseRouteSubsystem.Plo
	-rm -f snn/synapse/stdmem/$(DEPDIR)/SnnPESubComponent_mem.Plo
	-rm -f snn/synapse/stdmem/$(DEPDIR)/StdMemEndpoint.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/SnnBcsrWeightManager.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/SnnWeightDiagnostics.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightAccessor.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightCacheOps.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystem.Plo
	-rm -f snn/synapse/weights/$(DEPDIR)/WeightMemorySubsystemVerification.Plo
	-rm -f workloads/$(DEPDIR)/CoreWorkloadFactory.Plo
	-rm -f workloads/common/$(DEPDIR)/SnnAccelBackend.Plo
	-rm -f workloads/layout/$(DEPDIR)/NormalizedNeuronLayout.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnBootDriver.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnFirmwareLoader.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnHart.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnIss.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnRuntimeBridgeBackend.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowRuntimeServices.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnShadowTransportExport.Plo
	-rm -f workloads/riscv_snn/$(DEPDIR)/RiscvSnnWorkload.Plo
	-rm -f workloads/snn/$(DEPDIR)/SnnWorkload.Plo
	-rm -f workloads/stream/$(DEPDIR)/StreamWorkload.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkload.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadCollective.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadConfig.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadProgram.Plo
	-rm -f workloads/tensor/$(DEPDIR)/TensorWorkloadStats.Plo
	-rm -f workloads/traffic/$(DEPDIR)/TrafficWorkload.Plo
	-rm -f workloads/traffic_mem/$(DEPDIR)/TrafficMemWorkload.Plo
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

snippets: snippets-am

snippets-am: snippets-local

uninstall-am: uninstall-compLTLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles check check-am clean \
	clean-compLTLIBRARIES clean-generic clean-libtool \
	cscopelist-am ctags ctags-am distclean distclean-compile \
	distclean-generic distclean-libtool distclean-tags distdir dvi \
	dvi-am html html-am info info-am install install-am \
	install-compLTLIBRARIES install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am snippets-am \
	snippets-local tags tags-am uninstall uninstall-am \
	uninstall-compLTLIBRARIES

.PRECIOUS: Makefile


# 可选的MPI链接库 - 暂时注释掉
# if SST_CONFIG_HAVE_MPI
# libSnnDL_la_LDFLAGS += $(MPI_LDFLAGS)
# libSnnDL_la_LIBADD = $(MPI_LIBS)
# endif

.PHONY: test-compile test-riscv-snn-protocols test-riscv-snn-backend-timing-contract test-riscv-snn-runtime-service-provider test-riscv-snn-runtime-bridge-backend test-riscv-snn-firmware-protocol test-riscv-snn-toolchain-firmware-protocol test-riscv-snn-stimulus-gating
test-riscv-snn-protocols: test-riscv-snn-backend-timing-contract test-riscv-snn-runtime-service-provider test-riscv-snn-runtime-bridge-backend test-riscv-snn-firmware-protocol test-riscv-snn-toolchain-firmware-protocol test-riscv-snn-stimulus-gating

test-riscv-snn-stimulus-gating:
	$(RISCV_SNN_TEST_LINK) $(srcdir)/tests/test_riscv_snn_stimulus_gating.cc \
		-o $(builddir)/test_riscv_snn_stimulus_gating$(EXEEXT) && \
		$(builddir)/test_riscv_snn_stimulus_gating$(EXEEXT) && \
		rg -q "ex_rt\\.enabled = workloadAllowsSnnStimulus\\(cfg\\.workload_kind\\);" $(srcdir)/components/MultiCorePE.cc && \
		rg -q "if \\(!rt_\\.enabled\\)" $(srcdir)/snn/stimulus/ExternalSpikeInputSubsystem.cc

test-riscv-snn-backend-timing-contract:
	$(RISCV_SNN_TEST_LINK) $(srcdir)/tests/test_riscv_snn_backend_timing_contract.cc \
		$(srcdir)/workloads/common/SnnAccelBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnHart.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnIss.cc \
		-o $(builddir)/test_riscv_snn_backend_timing_contract$(EXEEXT) && \
		$(builddir)/test_riscv_snn_backend_timing_contract$(EXEEXT)

test-riscv-snn-runtime-service-provider:
	$(RISCV_SNN_TEST_LINK) $(srcdir)/tests/test_riscv_snn_runtime_service_provider.cc \
		$(srcdir)/workloads/common/SnnAccelBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnShadowTransportExport.cc \
		-o $(builddir)/test_riscv_snn_runtime_service_provider$(EXEEXT) && \
		$(builddir)/test_riscv_snn_runtime_service_provider$(EXEEXT)

test-riscv-snn-runtime-bridge-backend:
	$(RISCV_SNN_TEST_LINK) $(srcdir)/tests/test_riscv_snn_runtime_bridge_backend.cc \
		$(srcdir)/workloads/common/SnnAccelBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.cc \
		-o $(builddir)/test_riscv_snn_runtime_bridge_backend$(EXEEXT) && \
		$(builddir)/test_riscv_snn_runtime_bridge_backend$(EXEEXT)

test-riscv-snn-firmware-protocol:
	$(RISCV_SNN_TEST_LINK) $(srcdir)/tests/test_riscv_snn_firmware_protocol.cc \
		$(srcdir)/workloads/common/SnnAccelBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnHart.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnIss.cc \
		-o $(builddir)/test_riscv_snn_firmware_protocol$(EXEEXT) && \
		$(builddir)/test_riscv_snn_firmware_protocol$(EXEEXT)

test-riscv-snn-toolchain-firmware-protocol:
	$(RISCV_SNN_TEST_LINK) $(srcdir)/tests/test_riscv_snn_toolchain_firmware_protocol.cc \
		$(srcdir)/workloads/common/SnnAccelBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnRuntimeBridgeBackend.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnHart.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnIss.cc \
		$(srcdir)/workloads/riscv_snn/RiscvSnnFirmwareLoader.cc \
		-o $(builddir)/test_riscv_snn_toolchain_firmware_protocol$(EXEEXT) && \
		$(builddir)/test_riscv_snn_toolchain_firmware_protocol$(EXEEXT)

test-compile:
	$(CXXCOMPILE) -c $(srcdir)/tests/test_includes.cc -o $(builddir)/test_includes.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_abi.cc -o $(builddir)/test_riscv_snn_abi.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_backend_timing_contract.cc -o $(builddir)/test_riscv_snn_backend_timing_contract.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_boot_driver.cc -o $(builddir)/test_riscv_snn_boot_driver.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_firmware_loader.cc -o $(builddir)/test_riscv_snn_firmware_loader.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_firmware_tools.cc -o $(builddir)/test_riscv_snn_firmware_tools.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_firmware_protocol.cc -o $(builddir)/test_riscv_snn_firmware_protocol.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_toolchain_firmware_protocol.cc -o $(builddir)/test_riscv_snn_toolchain_firmware_protocol.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_iss.cc -o $(builddir)/test_riscv_snn_iss.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_queue_contract.cc -o $(builddir)/test_riscv_snn_queue_contract.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_runtime_bridge_backend.cc -o $(builddir)/test_riscv_snn_runtime_bridge_backend.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_runtime_service_provider.cc -o $(builddir)/test_riscv_snn_runtime_service_provider.o
	$(CXXCOMPILE) -c $(srcdir)/tests/test_riscv_snn_stimulus_gating.cc -o $(builddir)/test_riscv_snn_stimulus_gating.o

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
