// Generated by tools/export_snndl_v5_contracts.py; do not edit.
#pragma once
#include <array>

namespace SnnDL {
namespace v5 {

inline constexpr const char kStatisticsContractSha256[] = "5e3242dd9ae0011ea8422201e8f90f587969b2de99b5a8dbeeb17d526cbc4d75";
inline constexpr unsigned kStatisticNameCount = 84u;

inline constexpr const char kStatisticNameCacheL1Hits[] = "cache.l1.hits";
inline constexpr const char kStatisticNameCacheL1Misses[] = "cache.l1.misses";
inline constexpr const char kStatisticNameCacheL2Hits[] = "cache.l2.hits";
inline constexpr const char kStatisticNameCacheL2Misses[] = "cache.l2.misses";
inline constexpr const char kStatisticNameCoreAccumulatorAccepted[] = "core.accumulator.accepted";
inline constexpr const char kStatisticNameCoreAccumulatorBusyCycles[] = "core.accumulator.busy_cycles";
inline constexpr const char kStatisticNameCoreAccumulatorCompleted[] = "core.accumulator.completed";
inline constexpr const char kStatisticNameCoreAccumulatorFullCycles[] = "core.accumulator.full_cycles";
inline constexpr const char kStatisticNameCoreAccumulatorIssued[] = "core.accumulator.issued";
inline constexpr const char kStatisticNameCoreAccumulatorOccupancy[] = "core.accumulator.occupancy";
inline constexpr const char kStatisticNameCoreAccumulatorStallCycles[] = "core.accumulator.stall_cycles";
inline constexpr const char kStatisticNameCoreHeldSpikeAccepted[] = "core.held_spike.accepted";
inline constexpr const char kStatisticNameCoreHeldSpikeFullCycles[] = "core.held_spike.full_cycles";
inline constexpr const char kStatisticNameCoreHeldSpikeOccupancy[] = "core.held_spike.occupancy";
inline constexpr const char kStatisticNameCoreHeldSpikeReleased[] = "core.held_spike.released";
inline constexpr const char kStatisticNameCoreHeldSpikeStallCycles[] = "core.held_spike.stall_cycles";
inline constexpr const char kStatisticNameCoreIngressAccepted[] = "core.ingress.accepted";
inline constexpr const char kStatisticNameCoreIngressFullCycles[] = "core.ingress.full_cycles";
inline constexpr const char kStatisticNameCoreIngressOccupancy[] = "core.ingress.occupancy";
inline constexpr const char kStatisticNameCoreIngressStallCycles[] = "core.ingress.stall_cycles";
inline constexpr const char kStatisticNameCoreNeuronBusyCycles[] = "core.neuron.busy_cycles";
inline constexpr const char kStatisticNameCoreNeuronEvaluated[] = "core.neuron.evaluated";
inline constexpr const char kStatisticNameCoreNeuronFired[] = "core.neuron.fired";
inline constexpr const char kStatisticNameCoreNeuronOccupancy[] = "core.neuron.occupancy";
inline constexpr const char kStatisticNameCoreNeuronStallCycles[] = "core.neuron.stall_cycles";
inline constexpr const char kStatisticNameCoreRetireAccepted[] = "core.retire.accepted";
inline constexpr const char kStatisticNameCoreRetireBusyCycles[] = "core.retire.busy_cycles";
inline constexpr const char kStatisticNameCoreRetireCompleted[] = "core.retire.completed";
inline constexpr const char kStatisticNameCoreRetireFullCycles[] = "core.retire.full_cycles";
inline constexpr const char kStatisticNameCoreRetireIssued[] = "core.retire.issued";
inline constexpr const char kStatisticNameCoreRetireOccupancy[] = "core.retire.occupancy";
inline constexpr const char kStatisticNameCoreRetireRetired[] = "core.retire.retired";
inline constexpr const char kStatisticNameCoreRetireStallCycles[] = "core.retire.stall_cycles";
inline constexpr const char kStatisticNameCoreRowLookupAccepted[] = "core.row_lookup.accepted";
inline constexpr const char kStatisticNameCoreRowLookupBusyCycles[] = "core.row_lookup.busy_cycles";
inline constexpr const char kStatisticNameCoreRowLookupCompleted[] = "core.row_lookup.completed";
inline constexpr const char kStatisticNameCoreRowLookupFullCycles[] = "core.row_lookup.full_cycles";
inline constexpr const char kStatisticNameCoreRowLookupIssued[] = "core.row_lookup.issued";
inline constexpr const char kStatisticNameCoreRowLookupOccupancy[] = "core.row_lookup.occupancy";
inline constexpr const char kStatisticNameCoreRowLookupStallCycles[] = "core.row_lookup.stall_cycles";
inline constexpr const char kStatisticNameCoreSynapseAccepted[] = "core.synapse.accepted";
inline constexpr const char kStatisticNameCoreSynapseBusyCycles[] = "core.synapse.busy_cycles";
inline constexpr const char kStatisticNameCoreSynapseCompleted[] = "core.synapse.completed";
inline constexpr const char kStatisticNameCoreSynapseFullCycles[] = "core.synapse.full_cycles";
inline constexpr const char kStatisticNameCoreSynapseIssued[] = "core.synapse.issued";
inline constexpr const char kStatisticNameCoreSynapseOccupancy[] = "core.synapse.occupancy";
inline constexpr const char kStatisticNameCoreSynapseRows[] = "core.synapse.rows";
inline constexpr const char kStatisticNameCoreSynapseStallCycles[] = "core.synapse.stall_cycles";
inline constexpr const char kStatisticNameDmaBytes[] = "dma.bytes";
inline constexpr const char kStatisticNameDmaDescriptors[] = "dma.descriptors";
inline constexpr const char kStatisticNameDramBytes[] = "dram.bytes";
inline constexpr const char kStatisticNameDramRequests[] = "dram.requests";
inline constexpr const char kStatisticNameDramResponses[] = "dram.responses";
inline constexpr const char kStatisticNameNocCoreRetryCycles[] = "noc.core_retry_cycles";
inline constexpr const char kStatisticNameNocFlits[] = "noc.flits";
inline constexpr const char kStatisticNameNocLogicalDeliveries[] = "noc.logical_deliveries";
inline constexpr const char kStatisticNameNocPackets[] = "noc.packets";
inline constexpr const char kStatisticNameNocRxStallCycles[] = "noc.rx_stall_cycles";
inline constexpr const char kStatisticNameNocTxStallCycles[] = "noc.tx_stall_cycles";
inline constexpr const char kStatisticNameStorageDeltaReads[] = "storage.delta.reads";
inline constexpr const char kStatisticNameStorageSramBankConflicts[] = "storage.sram.bank_conflicts";
inline constexpr const char kStatisticNameStorageSramBusyCycles[] = "storage.sram.busy_cycles";
inline constexpr const char kStatisticNameStorageSramBytesRead[] = "storage.sram.bytes_read";
inline constexpr const char kStatisticNameStorageSramBytesWritten[] = "storage.sram.bytes_written";
inline constexpr const char kStatisticNameStorageSramCapacityBytes[] = "storage.sram.capacity_bytes";
inline constexpr const char kStatisticNameStorageSramLatencyCycles[] = "storage.sram.latency_cycles";
inline constexpr const char kStatisticNameStorageSramPortStallCycles[] = "storage.sram.port_stall_cycles";
inline constexpr const char kStatisticNameStorageSramQueueOccupancy[] = "storage.sram.queue_occupancy";
inline constexpr const char kStatisticNameStorageSramReads[] = "storage.sram.reads";
inline constexpr const char kStatisticNameStorageSramRequestsAccepted[] = "storage.sram.requests.accepted";
inline constexpr const char kStatisticNameStorageSramRequestsCapacityRejects[] = "storage.sram.requests.capacity_rejects";
inline constexpr const char kStatisticNameStorageSramRequestsCompleted[] = "storage.sram.requests.completed";
inline constexpr const char kStatisticNameStorageSramRequestsIssued[] = "storage.sram.requests.issued";
inline constexpr const char kStatisticNameStorageSramRequestsRetryableRejects[] = "storage.sram.requests.retryable_rejects";
inline constexpr const char kStatisticNameStorageSramResidentBytes[] = "storage.sram.resident_bytes";
inline constexpr const char kStatisticNameStorageSramResponseOccupancy[] = "storage.sram.response_occupancy";
inline constexpr const char kStatisticNameStorageSramWrites[] = "storage.sram.writes";
inline constexpr const char kStatisticNameStorageStateReads[] = "storage.state.reads";
inline constexpr const char kStatisticNameSyncBarrierWaitNs[] = "sync.barrier_wait_ns";
inline constexpr const char kStatisticNameTimestepCommitted[] = "timestep.committed";
inline constexpr const char kStatisticNameTimestepCoreElapsedNs[] = "timestep.core_elapsed_ns";
inline constexpr const char kStatisticNameTimestepElapsedNs[] = "timestep.elapsed_ns";
inline constexpr const char kStatisticNameTimestepSealed[] = "timestep.sealed";
inline constexpr const char kStatisticNameTimestepStarted[] = "timestep.started";

inline constexpr std::array<const char*, kStatisticNameCount> kStatisticNames = {
    kStatisticNameCacheL1Hits,
    kStatisticNameCacheL1Misses,
    kStatisticNameCacheL2Hits,
    kStatisticNameCacheL2Misses,
    kStatisticNameCoreAccumulatorAccepted,
    kStatisticNameCoreAccumulatorBusyCycles,
    kStatisticNameCoreAccumulatorCompleted,
    kStatisticNameCoreAccumulatorFullCycles,
    kStatisticNameCoreAccumulatorIssued,
    kStatisticNameCoreAccumulatorOccupancy,
    kStatisticNameCoreAccumulatorStallCycles,
    kStatisticNameCoreHeldSpikeAccepted,
    kStatisticNameCoreHeldSpikeFullCycles,
    kStatisticNameCoreHeldSpikeOccupancy,
    kStatisticNameCoreHeldSpikeReleased,
    kStatisticNameCoreHeldSpikeStallCycles,
    kStatisticNameCoreIngressAccepted,
    kStatisticNameCoreIngressFullCycles,
    kStatisticNameCoreIngressOccupancy,
    kStatisticNameCoreIngressStallCycles,
    kStatisticNameCoreNeuronBusyCycles,
    kStatisticNameCoreNeuronEvaluated,
    kStatisticNameCoreNeuronFired,
    kStatisticNameCoreNeuronOccupancy,
    kStatisticNameCoreNeuronStallCycles,
    kStatisticNameCoreRetireAccepted,
    kStatisticNameCoreRetireBusyCycles,
    kStatisticNameCoreRetireCompleted,
    kStatisticNameCoreRetireFullCycles,
    kStatisticNameCoreRetireIssued,
    kStatisticNameCoreRetireOccupancy,
    kStatisticNameCoreRetireRetired,
    kStatisticNameCoreRetireStallCycles,
    kStatisticNameCoreRowLookupAccepted,
    kStatisticNameCoreRowLookupBusyCycles,
    kStatisticNameCoreRowLookupCompleted,
    kStatisticNameCoreRowLookupFullCycles,
    kStatisticNameCoreRowLookupIssued,
    kStatisticNameCoreRowLookupOccupancy,
    kStatisticNameCoreRowLookupStallCycles,
    kStatisticNameCoreSynapseAccepted,
    kStatisticNameCoreSynapseBusyCycles,
    kStatisticNameCoreSynapseCompleted,
    kStatisticNameCoreSynapseFullCycles,
    kStatisticNameCoreSynapseIssued,
    kStatisticNameCoreSynapseOccupancy,
    kStatisticNameCoreSynapseRows,
    kStatisticNameCoreSynapseStallCycles,
    kStatisticNameDmaBytes,
    kStatisticNameDmaDescriptors,
    kStatisticNameDramBytes,
    kStatisticNameDramRequests,
    kStatisticNameDramResponses,
    kStatisticNameNocCoreRetryCycles,
    kStatisticNameNocFlits,
    kStatisticNameNocLogicalDeliveries,
    kStatisticNameNocPackets,
    kStatisticNameNocRxStallCycles,
    kStatisticNameNocTxStallCycles,
    kStatisticNameStorageDeltaReads,
    kStatisticNameStorageSramBankConflicts,
    kStatisticNameStorageSramBusyCycles,
    kStatisticNameStorageSramBytesRead,
    kStatisticNameStorageSramBytesWritten,
    kStatisticNameStorageSramCapacityBytes,
    kStatisticNameStorageSramLatencyCycles,
    kStatisticNameStorageSramPortStallCycles,
    kStatisticNameStorageSramQueueOccupancy,
    kStatisticNameStorageSramReads,
    kStatisticNameStorageSramRequestsAccepted,
    kStatisticNameStorageSramRequestsCapacityRejects,
    kStatisticNameStorageSramRequestsCompleted,
    kStatisticNameStorageSramRequestsIssued,
    kStatisticNameStorageSramRequestsRetryableRejects,
    kStatisticNameStorageSramResidentBytes,
    kStatisticNameStorageSramResponseOccupancy,
    kStatisticNameStorageSramWrites,
    kStatisticNameStorageStateReads,
    kStatisticNameSyncBarrierWaitNs,
    kStatisticNameTimestepCommitted,
    kStatisticNameTimestepCoreElapsedNs,
    kStatisticNameTimestepElapsedNs,
    kStatisticNameTimestepSealed,
    kStatisticNameTimestepStarted,
};

}  // namespace v5
}  // namespace SnnDL
